-- 개정이력: 2026.06.17  구재호  전 DBMS TB_ 표준 명명 현행화
CREATE TABLE IDS  (
  TABLE_NAME varchar(60) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE COMTECOPSEQ (
  TABLE_NAME varchar(20) DEFAULT '' NOT NULL,
  NEXT_ID numeric(30,0) DEFAULT 0 NOT NULL,
  CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
) ;

CREATE TABLE TB_CMMN_CL_CODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(180) ,
  CL_CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CMMN_CL_CODE_PK PRIMARY KEY (CL_CODE)
) ;

CREATE TABLE TB_CMMN_CODE (
  CODE_ID varchar(18) NOT NULL,
  CODE_ID_NM varchar(180) ,
  CODE_ID_DC varchar(600) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CMMN_CODE_PK PRIMARY KEY (CODE_ID)
) ;

CREATE TABLE TB_CMMN_DETAIL_CODE (
  CODE_ID varchar(18) NOT NULL,
  CODE varchar(45) NOT NULL,
  CODE_NM varchar(180) ,
  CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_CMMN_DETAIL_CODE_PK PRIMARY KEY (CODE_ID,CODE)
) ;

CREATE TABLE TB_ORGNZT_INFO (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar(60) NOT NULL,
  ORGNZT_DC varchar(300) ,
  CONSTRAINT TB_ORGNZT_INFO_PK PRIMARY KEY (ORGNZT_ID)
) ;

CREATE TABLE TB_AUTHOR_GROUP_INFO (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar(180) NOT NULL,
  GROUP_CREAT_DE char(60) NOT NULL,
  GROUP_DC varchar(300) ,
  CONSTRAINT TB_AUTHOR_GROUP_INFO_PK PRIMARY KEY (GROUP_ID)
) ;

CREATE TABLE TB_AUTHOR_INFO (
  AUTHOR_CODE varchar(90) DEFAULT '' NOT NULL,
  AUTHOR_NM varchar(180) NOT NULL,
  AUTHOR_DC varchar(600) ,
  AUTHOR_CREAT_DE char(60) NOT NULL,
  CONSTRAINT TB_AUTHOR_INFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;

CREATE TABLE TB_ROLES_HIERARCHY (
  PARNTS_ROLE varchar(90) NOT NULL,
  CHLDRN_ROLE varchar(90) NOT NULL,
  CONSTRAINT TB_ROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE)
) ;

CREATE TABLE TB_ROLE_INFO (
  ROLE_CODE varchar(150) DEFAULT '' NOT NULL,
  ROLE_NM varchar(180) NOT NULL,
  ROLE_PTTRN varchar(900) ,
  ROLE_DC varchar(600) ,
  ROLE_TY varchar(240) ,
  ROLE_SORT varchar(30) ,
  ROLE_CREAT_DE char(60) NOT NULL,
  CONSTRAINT TB_ROLE_INFO_PK PRIMARY KEY (ROLE_CODE)
) ;

CREATE TABLE TB_AUTHOR_ROLE_RELATE (
  AUTHOR_CODE varchar(90) NOT NULL,
  ROLE_CODE varchar(150) NOT NULL,
  CREAT_DT DATETIME ,
  CONSTRAINT TB_AUTHOR_ROLE_RELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE)
) ;

CREATE TABLE TB_GNRL_MBER (
  MBER_ID varchar(60) DEFAULT '' NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  PASSWORD_HINT varchar(300) NOT NULL,
  PASSWORD_CNSR varchar(300) NOT NULL,
  IHIDNUM varchar(39) ,
  MBER_NM varchar(150) NOT NULL,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  AREA_NO varchar(12) ,
  MBER_STTUS varchar(45) ,
  DETAIL_ADRES varchar(300) ,
  END_TELNO varchar(12) ,
  MBTLNUM varchar(60) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar(60) ,
  MBER_EMAIL_ADRES varchar(150) ,
  MIDDLE_TELNO varchar(12) ,
  SBSCRB_DE DATETIME ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT TB_GNRL_MBER_PK PRIMARY KEY (MBER_ID)
) ;

CREATE TABLE TB_EMPLYR_SCRTY_ESTBS (
  SCRTY_DTRMN_TRGET_ID varchar(60) NOT NULL,
  MBER_TY_CODE varchar(45) ,
  AUTHOR_CODE varchar(90) NOT NULL,
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID)
) ;

CREATE TABLE TB_TMPLAT_INFO (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,
  TMPLAT_NM varchar(765) ,
  TMPLAT_COURS varchar(6000) ,
  USE_AT char(1) ,
  TMPLAT_SE_CODE char(6) ,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT TB_TMPLAT_INFO_PK PRIMARY KEY (TMPLAT_ID)
) ;

CREATE TABLE TB_BBS_MASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(765) NOT NULL,
  BBS_INTRCN varchar(7200) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT TB_BBS_MASTER_PK PRIMARY KEY (BBS_ID)
) ;

CREATE TABLE TB_BBS_USE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_BBS_USE_PK PRIMARY KEY (BBS_ID,TRGET_ID)
) ;

CREATE TABLE TB_BBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) ,
  NTT_SJ varchar(6000) ,
  NTT_CN STRING,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO numeric(10,0) ,
  ANSWER_LC numeric(8) ,
  SORT_ORDR numeric(8,0) ,
  RDCNT numeric(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar(60) ,
  NTCR_NM varchar(60) ,
  PASSWORD varchar(600) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_BBS_PK PRIMARY KEY (NTT_ID,BBS_ID)
) ;

CREATE TABLE TB_BBS_MASTER_OPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATETIME DEFAULT SYSDATE NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_BBS_MASTER_OPTN_PK PRIMARY KEY (BBS_ID)
) ;

CREATE TABLE TB_EMPLYR_INFO (
  EMPLYR_ID varchar(60) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar(180) NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  EMPL_NO varchar(60) ,
  IHIDNUM varchar(39) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(60) ,
  HOUSE_ADRES varchar(300) ,
  PASSWORD_HINT varchar(300) NOT NULL,
  PASSWORD_CNSR varchar(300) NOT NULL,
  HOUSE_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  DETAIL_ADRES varchar(300) ,
  ZIP varchar(18) ,
  OFFM_TELNO varchar(60) ,
  MBTLNUM varchar(60) ,
  EMAIL_ADRES varchar(150) ,
  OFCPS_NM varchar(180) ,
  HOUSE_MIDDLE_TELNO varchar(12) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(45) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(60) ,
  SBSCRB_DE DATETIME ,
  CONSTRAINT TB_EMPLYR_INFO_PK PRIMARY KEY (EMPLYR_ID)
) ;

CREATE TABLE TB_EMPLYR_INFO_CHNG_DTLS (
  EMPLYR_ID varchar(60) NOT NULL,
  CHANGE_DE char(20) NOT NULL,
  ORGNZT_ID char(20) ,
  GROUP_ID char(20) ,
  EMPL_NO varchar(60) NOT NULL,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(60) ,
  HOUSE_ADRES varchar(300) NOT NULL,
  HOUSE_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  DETAIL_ADRES varchar(300) NOT NULL,
  ZIP varchar(18) NOT NULL,
  OFFM_TELNO varchar(60) ,
  MBTLNUM varchar(60) NOT NULL,
  EMAIL_ADRES varchar(150) ,
  HOUSE_MIDDLE_TELNO varchar(12) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(45) NOT NULL,
  ESNTL_ID char(20) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_PK PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
) ;

CREATE TABLE TB_ZIP (
  ZIP varchar(18) NOT NULL,
  SN numeric(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM varchar(60) ,
  SIGNGU_NM varchar(60) ,
  EMD_NM varchar(180) ,
  LI_BULD_NM varchar(180) ,
  LNBR_DONG_HO varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_ZIP_PK PRIMARY KEY (ZIP,SN)
) ;

CREATE TABLE TB_BANNER (
  BANNER_ID char(20) DEFAULT '' NOT NULL,
  BANNER_NM varchar(180) NOT NULL,
  LINK_URL varchar(765) NOT NULL,
  BANNER_IMAGE varchar(180) NOT NULL,
  BANNER_DC varchar(600) ,
  REFLCT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  BANNER_IMAGE_FILE varchar(180) ,
  SORT_ORDR numeric(8,0) ,
  BANNER_TY varchar(10) DEFAULT 'MAIN',
  POPUP_LEFT integer ,
  POPUP_TOP integer ,
  POPUP_WIDTH integer ,
  POPUP_HEIGHT integer ,
  POPUP_GROUP_AT char(1) DEFAULT 'N',
  EXPSR_BGNDE DATE ,
  EXPSR_ENDDE DATE ,
  CONSTRAINT TB_BANNER_PK PRIMARY KEY (BANNER_ID)
) ;

CREATE TABLE TB_ENTRPRS_MBER (
  ENTRPRS_MBER_ID varchar(60) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar(30) ,
  JURIRNO varchar(39) ,
  CMPNY_NM varchar(180) NOT NULL,
  CXFC varchar(150) ,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  ENTRPRS_MIDDLE_TELNO varchar(12) ,
  FXNUM varchar(60) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar(150) ,
  APPLCNT_IHIDNUM varchar(39) ,
  SBSCRB_DE DATETIME ,
  ENTRPRS_MBER_STTUS varchar(45) ,
  ENTRPRS_MBER_PASSWORD varchar(600) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(300) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(300) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar(300) ,
  ENTRPRS_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  APPLCNT_EMAIL_ADRES varchar(150) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT TB_ENTRPRS_MBER_PK PRIMARY KEY (ENTRPRS_MBER_ID)
) ;

CREATE TABLE TB_FILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATETIME NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT TB_FILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;

CREATE TABLE TB_FILE_DETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(6000) NOT NULL,
  STRE_FILE_NM varchar(765) NOT NULL,
  ORIGNL_FILE_NM varchar(765) ,
  FILE_EXTSN varchar(60) NOT NULL,
  FILE_CN STRING,
  FILE_SIZE numeric(8,0) ,
  CONSTRAINT TB_FILE_DETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN)
) ;

CREATE TABLE TB_FAQ_INFO (
  FAQ_ID char(20) NOT NULL,
  QESTN_SJ varchar(765) ,
  QESTN_CN varchar(7500) ,
  ANSWER_CN varchar(7500) ,
  RDCNT numeric(10,0) ,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID varchar(60) NOT NULL,
  ATCH_FILE_ID char(20) ,
  QNA_PROCESS_STTUS_CODE char(1) ,
  CONSTRAINT TB_FAQ_INFO_PK PRIMARY KEY (FAQ_ID)
) ;

CREATE TABLE TB_INDVDL_INFO_POLICY (
  INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,
  INDVDL_INFO_POLICY_CN varchar(7500) ,
  INDVDL_INFO_POLICY_AGRE_AT char(1) ,
  FRST_REGISTER_ID varchar(60) ,
  FRST_REGIST_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  INDVDL_INFO_POLICY_NM varchar(765) ,
  VER varchar(60) ,
  APLC_DE varchar(24) ,
  REPRSNT_AT char(1) DEFAULT 'N',
  CONSTRAINT TB_INDVDL_INFO_POLICY_PK PRIMARY KEY (INDVDL_INFO_POLICY_ID)
) ;

CREATE TABLE TB_PROGRM_LIST (
  PROGRM_FILE_NM varchar(180) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH varchar(300) NOT NULL,
  PROGRM_KOREAN_NM varchar(180) ,
  PROGRM_DC varchar(600) ,
  URL varchar(300) NOT NULL,
  CONSTRAINT TB_PROGRM_LIST_PK PRIMARY KEY (PROGRM_FILE_NM)
) ;

CREATE TABLE TB_MENU_INFO (
  MENU_NM varchar(180) NOT NULL,
  PROGRM_FILE_NM varchar(180) NOT NULL,
  MENU_NO numeric(20,0) NOT NULL,
  UPPER_MENU_NO numeric(20,0) ,
  MENU_ORDR numeric(5,0) NOT NULL,
  MENU_DC varchar(750) ,
  RELATE_IMAGE_PATH varchar(300) ,
  RELATE_IMAGE_NM varchar(180) ,
  CONSTRAINT TB_MENU_INFO_PK PRIMARY KEY (MENU_NO)
) ;

CREATE TABLE TB_MENU_CREAT_DTLS (
  MENU_NO numeric(20,0) NOT NULL,
  AUTHOR_CODE varchar(90) NOT NULL,
  MAPNG_CREAT_ID varchar(90) ,
  CONSTRAINT TB_MENU_CREAT_DTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE)
) ;

CREATE TABLE TB_QA_INFO (
  QA_ID char(20) NOT NULL,
  QESTN_SJ varchar(765) ,
  QESTN_CN varchar(7500) ,
  WRITNG_DE char(20) ,
  RDCNT numeric(10,0) ,
  EMAIL_ADRES varchar(150) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  QNA_PROCESS_STTUS_CODE char(1) ,
  WRTER_NM varchar(60) ,
  ANSWER_CN varchar(7500) ,
  WRITNG_PASSWORD varchar(60) ,
  ANSWER_DE char(20) ,
  EMAIL_ANSWER_AT char(1) ,
  AREA_NO varchar(12) ,
  MIDDLE_TELNO varchar(12) ,
  END_TELNO varchar(12) ,
  CONSTRAINT TB_QA_INFO_PK PRIMARY KEY (QA_ID)
) ;

CREATE TABLE TB_QUSTNR_TMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_TY varchar(300) ,
  QUSTNR_TMPLAT_DC varchar(6000) ,
  QUSTNR_TMPLAT_PATH_NM varchar(300) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  QUSTNR_TMPLAT_IMAGE_INFO blob,
  CONSTRAINT TB_QUSTNR_TMPLAT_PK PRIMARY KEY (QUSTNR_TMPLAT_ID)
) ;

CREATE TABLE TB_QESTNR_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_SJ varchar(765) ,
  QUSTNR_PURPS varchar(3000) ,
  QUSTNR_WRITNG_GUIDANCE_CN varchar(6000) ,
  QUSTNR_TRGET varchar(3000) ,
  QUSTNR_BGNDE char(20) ,
  QUSTNR_ENDDE char(20) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_QESTNR_INFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID)
) ;

CREATE TABLE TB_QUSTNR_QESITM (
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTN_SN numeric(10,0) ,
  QESTN_TY_CODE char(1) ,
  QESTN_CN varchar(7500) ,
  MXMM_CHOISE_CO numeric(5,0) ,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID varchar(60) NOT NULL,
  CONSTRAINT TB_QUSTNR_QESITM_PK PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
) ;

CREATE TABLE TB_QUSTNR_IEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_IEM_ID varchar(60) NOT NULL,
  IEM_SN numeric(5,0) ,
  IEM_CN varchar(3000) ,
  ETC_ANSWER_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_QUSTNR_IEM_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID)
) ;

CREATE TABLE TB_QUSTNR_RESPOND_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_RESPOND_ID char(20) NOT NULL,
  SEXDSTN_CODE char(1) ,
  OCCP_TY_CODE varchar(3) ,
  RESPOND_NM varchar(150) ,
  BRTHDY char(20) ,
  AREA_NO varchar(12) ,
  MIDDLE_TELNO varchar(12) ,
  END_TELNO varchar(12) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_QUSTNR_RESPOND_INFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID)
) ;

CREATE TABLE TB_QUSTNR_RSPNS_RESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  RESPOND_ANSWER_CN varchar(3000) ,
  ETC_ANSWER_CN varchar(3000) ,
  RESPOND_NM varchar(150) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  QUSTNR_IEM_ID varchar(60) ,
  CONSTRAINT TB_QUSTNR_RSPNS_RESULT_PK PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
) ;

CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID char(20) NOT NULL,
  USE_STPLAT_NM varchar(300) ,
  USE_STPLAT_CN STRING,
  INFO_PROVD_AGRE_CN STRING,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  VER varchar(60) ,
  APLC_DE varchar(24) ,
  REPRSNT_AT char(1) DEFAULT 'N',
  CONSTRAINT TB_STPLAT_INFO_PK PRIMARY KEY (USE_STPLAT_ID)
) ;

CREATE TABLE TB_SCHDUL_INFO (
  SCHDUL_ID char(20) NOT NULL,
  SCHDUL_SE char(1) ,
  SCHDUL_DEPT_ID varchar(20) ,
  SCHDUL_KND_CODE varchar(20) ,
  SCHDUL_BEGINDE DATETIME ,
  SCHDUL_ENDDE DATETIME ,
  SCHDUL_NM varchar(255) ,
  SCHDUL_CN varchar(2500) ,
  SCHDUL_PLACE varchar(255) ,
  SCHDUL_IPCR_CODE char(1) ,
  SCHDUL_CHARGER_ID varchar(20) ,
  ATCH_FILE_ID char(20) ,
  REPTIT_SE_CODE char(3) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_SCHDUL_INFO_PK PRIMARY KEY (SCHDUL_ID)
) ;

CREATE TABLE TB_RESTDE (
  RESTDE_NO numeric(20,0) NOT NULL,
  RESTDE_DE char(8) NOT NULL,
  RESTDE_NM varchar(100) NOT NULL,
  RESTDE_DC varchar(200) ,
  RESTDE_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT TB_RESTDE_PK PRIMARY KEY (RESTDE_NO)
) ;

CREATE OR REPLACE VIEW VW_USER_MASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_GNRL_MBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM TB_EMPLYR_INFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_ENTRPRS_MBER 
;