-- 개정이력: 2026.06.17  구재호  전 DBMS TB_ 표준 명명 현행화
DROP TABLE IDS CASCADE CONSTRAINTS;
CREATE TABLE IDS  (
  TABLE_NAME varchar2(20) NOT NULL,
  NEXT_ID number(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
DROP TABLE TB_CMMN_CL_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_CL_CODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar2(60) ,
  CL_CODE_DC varchar2(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CMMN_CL_CODE_PK PRIMARY KEY (CL_CODE)
) ;
DROP TABLE TB_CMMN_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_CODE (
  CODE_ID varchar2(6) NOT NULL,
  CODE_ID_NM varchar2(60) ,
  CODE_ID_DC varchar2(200) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CMMN_CODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT TB_CMMN_CODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES TB_CMMN_CL_CODE (CL_CODE)
) ;
DROP TABLE TB_CMMN_DETAIL_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_DETAIL_CODE (
  CODE_ID varchar2(6) NOT NULL,
  CODE varchar2(15) NOT NULL,
  CODE_NM varchar2(60) ,
  CODE_DC varchar2(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_CMMN_DETAIL_CODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT TB_CMMN_DETAIL_CODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES TB_CMMN_CODE (CODE_ID)
) ;
DROP TABLE TB_ORGNZT_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_ORGNZT_INFO (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar2(20) NOT NULL,
  ORGNZT_DC varchar2(100) ,
  CONSTRAINT TB_ORGNZT_INFO_PK PRIMARY KEY (ORGNZT_ID)
) ;
DROP TABLE TB_AUTHOR_GROUP_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_AUTHOR_GROUP_INFO (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar2(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC varchar2(100) ,
  CONSTRAINT TB_AUTHOR_GROUP_INFO_PK PRIMARY KEY (GROUP_ID)
) ;
DROP TABLE TB_AUTHOR_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_AUTHOR_INFO (
  AUTHOR_CODE varchar2(30) DEFAULT '' NOT NULL,
  AUTHOR_NM varchar2(60) NOT NULL,
  AUTHOR_DC varchar2(200) ,
  AUTHOR_CREAT_DE char(20) NOT NULL,
  CONSTRAINT TB_AUTHOR_INFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;
DROP TABLE TB_ROLES_HIERARCHY CASCADE CONSTRAINTS;
CREATE TABLE TB_ROLES_HIERARCHY (
  PARNTS_ROLE varchar2(30) NOT NULL,
  CHLDRN_ROLE varchar2(30) NOT NULL,
  CONSTRAINT TB_ROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT TB_ROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT TB_ROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE
) ;
DROP TABLE TB_ROLE_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_ROLE_INFO (
  ROLE_CODE varchar2(50) DEFAULT '' NOT NULL,
  ROLE_NM varchar2(60) NOT NULL,
  ROLE_PTTRN varchar2(300) ,
  ROLE_DC varchar2(200) ,
  ROLE_TY varchar2(80) ,
  ROLE_SORT varchar2(10) ,
  ROLE_CREAT_DE char(20) NOT NULL,
  CONSTRAINT TB_ROLE_INFO_PK PRIMARY KEY (ROLE_CODE)
) ;
DROP TABLE TB_AUTHOR_ROLE_RELATE CASCADE CONSTRAINTS;
CREATE TABLE TB_AUTHOR_ROLE_RELATE (
  AUTHOR_CODE varchar2(30) NOT NULL,
  ROLE_CODE varchar2(50) NOT NULL,
  CREAT_DT DATE ,
  CONSTRAINT TB_AUTHOR_ROLE_RELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT TB_AUTHOR_ROLE_RELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES TB_ROLE_INFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT TB_AUTHOR_ROLE_RELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE
) ;
DROP TABLE TB_GNRL_MBER CASCADE CONSTRAINTS;
CREATE TABLE TB_GNRL_MBER (
  MBER_ID varchar2(20) DEFAULT '' NOT NULL,
  PASSWORD varchar2(200) NOT NULL,
  PASSWORD_HINT varchar2(100) NOT NULL,
  PASSWORD_CNSR varchar2(100) NOT NULL,
  IHIDNUM varchar2(200) ,
  MBER_NM varchar2(50) NOT NULL,
  ZIP varchar2(6) ,
  ADRES varchar2(100) ,
  AREA_NO varchar2(4) ,
  MBER_STTUS varchar2(15) ,
  DETAIL_ADRES varchar2(100) ,
  END_TELNO varchar2(4) ,
  MBTLNUM varchar2(20) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar2(20) ,
  MBER_EMAIL_ADRES varchar2(50) ,
  MIDDLE_TELNO varchar2(4) ,
  SBSCRB_DE DATE ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT TB_GNRL_MBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT TB_GNRL_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_EMPLYR_SCRTY_ESTBS CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_SCRTY_ESTBS (
  SCRTY_DTRMN_TRGET_ID varchar2(20) NOT NULL,
  MBER_TY_CODE varchar2(15) ,
  AUTHOR_CODE varchar2(30) NOT NULL,
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE)
) ;
DROP TABLE TB_TMPLAT_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_TMPLAT_INFO (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,
  TMPLAT_NM varchar2(255) ,
  TMPLAT_COURS varchar2(2000) ,
  USE_AT char(1) ,
  TMPLAT_SE_CODE char(6) ,
  FRST_REGISTER_ID varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT TB_TMPLAT_INFO_PK PRIMARY KEY (TMPLAT_ID)
) ;
DROP TABLE TB_BBS_MASTER CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_MASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar2(255) NOT NULL,
  BBS_INTRCN varchar2(2400) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER number(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE number(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  FRST_REGIST_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT TB_BBS_MASTER_PK PRIMARY KEY (BBS_ID)
) ;
DROP TABLE TB_BBS_USE CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_USE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_BBS_USE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT TB_BBS_USE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;
DROP TABLE TB_BBS CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS (
  NTT_ID number(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO number(20,0) ,
  NTT_SJ varchar2(2000) ,
  NTT_CN CLOB,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO number(10,0) ,
  ANSWER_LC number(8) ,
  SORT_ORDR number(8,0) ,
  RDCNT number(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar2(20) ,
  NTCR_NM varchar2(20) ,
  PASSWORD varchar2(200) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_BBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT TB_BBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;
DROP TABLE TB_BBS_MASTER_OPTN CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_MASTER_OPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT SYSDATE NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_BBS_MASTER_OPTN_PK PRIMARY KEY (BBS_ID)
) ;
DROP TABLE TB_EMPLYR_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_INFO (
  EMPLYR_ID varchar2(20) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar2(60) NOT NULL,
  PASSWORD varchar2(200) NOT NULL,
  EMPL_NO varchar2(20) ,
  IHIDNUM varchar2(200) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar2(20) ,
  HOUSE_ADRES varchar2(100) ,
  PASSWORD_HINT varchar2(100) NOT NULL,
  PASSWORD_CNSR varchar2(100) NOT NULL,
  HOUSE_END_TELNO varchar2(4) ,
  AREA_NO varchar2(4) ,
  DETAIL_ADRES varchar2(100) ,
  ZIP varchar2(6) ,
  OFFM_TELNO varchar2(20) ,
  MBTLNUM varchar2(20) ,
  EMAIL_ADRES varchar2(50) ,
  OFCPS_NM varchar2(60) ,
  HOUSE_MIDDLE_TELNO varchar2(4) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar2(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar2(20) ,
  SBSCRB_DE DATE ,
  CONSTRAINT TB_EMPLYR_INFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT TB_EMPLYR_INFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT TB_EMPLYR_INFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES TB_ORGNZT_INFO (ORGNZT_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_ZIP CASCADE CONSTRAINTS;
CREATE TABLE TB_ZIP (
  ZIP varchar2(6) NOT NULL,
  SN number(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM varchar2(20) ,
  SIGNGU_NM varchar2(20) ,
  EMD_NM varchar2(60) ,
  LI_BULD_NM varchar2(60) ,
  LNBR_DONG_HO varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_ZIP_PK PRIMARY KEY (ZIP,SN)
) ;
DROP TABLE TB_BANNER CASCADE CONSTRAINTS;
CREATE TABLE TB_BANNER (
  BANNER_ID char(20) DEFAULT '' NOT NULL,
  BANNER_NM varchar2(60) NOT NULL,
  LINK_URL varchar2(255) NOT NULL,
  BANNER_IMAGE varchar2(60) NOT NULL,
  BANNER_DC varchar2(200) ,
  REFLCT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  BANNER_IMAGE_FILE varchar2(60) ,
  SORT_ORDR number(8,0) ,
  BANNER_TY varchar(10) DEFAULT 'MAIN',
  CONSTRAINT TB_BANNER_PK PRIMARY KEY (BANNER_ID)
) ;
DROP TABLE TB_ENTRPRS_MBER CASCADE CONSTRAINTS;
CREATE TABLE TB_ENTRPRS_MBER (
  ENTRPRS_MBER_ID varchar2(20) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar2(10) ,
  JURIRNO varchar2(13) ,
  CMPNY_NM varchar2(60) NOT NULL,
  CXFC varchar2(50) ,
  ZIP varchar2(6) ,
  ADRES varchar2(100) ,
  ENTRPRS_MIDDLE_TELNO varchar2(4) ,
  FXNUM varchar2(20) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar2(50) ,
  APPLCNT_IHIDNUM varchar2(200) ,
  SBSCRB_DE DATE ,
  ENTRPRS_MBER_STTUS varchar2(15) ,
  ENTRPRS_MBER_PASSWORD varchar2(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar2(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar2(100) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar2(100) ,
  ENTRPRS_END_TELNO varchar2(4) ,
  AREA_NO varchar2(4) ,
  APPLCNT_EMAIL_ADRES varchar2(50) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT TB_ENTRPRS_MBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT TB_ENTRPRS_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_FILE CASCADE CONSTRAINTS;
CREATE TABLE TB_FILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATE NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT TB_FILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;
DROP TABLE TB_FILE_DETAIL CASCADE CONSTRAINTS;
CREATE TABLE TB_FILE_DETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN number(10,0) NOT NULL,
  FILE_STRE_COURS varchar2(2000) NOT NULL,
  STRE_FILE_NM varchar2(255) NOT NULL,
  ORIGNL_FILE_NM varchar2(255) ,
  FILE_EXTSN varchar2(20) NOT NULL,
  FILE_CN CLOB,
  FILE_SIZE number(8,0) ,
  CONSTRAINT TB_FILE_DETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT TB_FILE_DETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE (ATCH_FILE_ID)
) ;
DROP TABLE TB_FAQ_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_FAQ_INFO (
  FAQ_ID char(20) NOT NULL,
  QESTN_SJ varchar2(255) ,
  QESTN_CN varchar2(2500) ,
  ANSWER_CN varchar2(2500) ,
  RDCNT number(10,0) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID varchar2(20) NOT NULL,
  ATCH_FILE_ID char(20) ,
  QNA_PROCESS_STTUS_CODE char(1) ,
  CONSTRAINT TB_FAQ_INFO_PK PRIMARY KEY (FAQ_ID),
  CONSTRAINT TB_FAQ_INFO_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE (ATCH_FILE_ID)
) ;
DROP TABLE TB_INDVDL_INFO_POLICY CASCADE CONSTRAINTS;
CREATE TABLE TB_INDVDL_INFO_POLICY (
  INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,
  INDVDL_INFO_POLICY_CN varchar2(2500) ,
  INDVDL_INFO_POLICY_AGRE_AT char(1) ,
  FRST_REGISTER_ID varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  INDVDL_INFO_POLICY_NM varchar2(255) ,
  CONSTRAINT TB_INDVDL_INFO_POLICY_PK PRIMARY KEY (INDVDL_INFO_POLICY_ID)
) ;
DROP TABLE TB_PROGRM_LIST CASCADE CONSTRAINTS;
CREATE TABLE TB_PROGRM_LIST (
  PROGRM_FILE_NM varchar2(60) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH varchar2(100) NOT NULL,
  PROGRM_KOREAN_NM varchar2(60) ,
  PROGRM_DC varchar2(200) ,
  URL varchar2(100) NOT NULL,
  CONSTRAINT TB_PROGRM_LIST_PK PRIMARY KEY (PROGRM_FILE_NM)
) ;
DROP TABLE TB_MENU_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_MENU_INFO (
  MENU_NM varchar2(60) NOT NULL,
  PROGRM_FILE_NM varchar2(60) NOT NULL,
  MENU_NO number(20,0) NOT NULL,
  UPPER_MENU_NO number(20,0) ,
  MENU_ORDR number(5,0) NOT NULL,
  MENU_DC varchar2(250) ,
  RELATE_IMAGE_PATH varchar2(100) ,
  RELATE_IMAGE_NM varchar2(60) ,
  CONSTRAINT TB_MENU_INFO_PK PRIMARY KEY (MENU_NO),
  CONSTRAINT TB_MENU_INFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES TB_MENU_INFO (MENU_NO),
  CONSTRAINT TB_MENU_INFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES TB_PROGRM_LIST (PROGRM_FILE_NM) ON DELETE CASCADE
) ;
DROP TABLE TB_MENU_CREAT_DTLS CASCADE CONSTRAINTS;
CREATE TABLE TB_MENU_CREAT_DTLS (
  MENU_NO number(20,0) NOT NULL,
  AUTHOR_CODE varchar2(30) NOT NULL,
  MAPNG_CREAT_ID varchar2(30) ,
  CONSTRAINT TB_MENU_CREAT_DTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT TB_MENU_CREAT_DTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE),
  CONSTRAINT TB_MENU_CREAT_DTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES TB_MENU_INFO (MENU_NO) ON DELETE CASCADE
) ;
DROP TABLE TB_QA_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_QA_INFO (
  QA_ID char(20) NOT NULL,
  QESTN_SJ varchar2(255) ,
  QESTN_CN varchar2(2500) ,
  WRITNG_DE char(20) ,
  RDCNT number(10,0) ,
  EMAIL_ADRES varchar2(50) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  QNA_PROCESS_STTUS_CODE char(1) ,
  WRTER_NM varchar2(20) ,
  ANSWER_CN varchar2(2500) ,
  WRITNG_PASSWORD varchar2(20) ,
  ANSWER_DE char(20) ,
  EMAIL_ANSWER_AT char(1) ,
  AREA_NO varchar2(4) ,
  MIDDLE_TELNO varchar2(4) ,
  END_TELNO varchar2(4) ,
  CONSTRAINT TB_QA_INFO_PK PRIMARY KEY (QA_ID)
) ;

DROP TABLE TB_QUSTNR_TMPLAT CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_TMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_TY varchar2(100) ,
  QUSTNR_TMPLAT_DC varchar2(2000) ,
  QUSTNR_TMPLAT_PATH_NM varchar2(100) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  QUSTNR_TMPLAT_IMAGE_INFO blob,
  CONSTRAINT TB_QUSTNR_TMPLAT_PK PRIMARY KEY (QUSTNR_TMPLAT_ID)
) ;

DROP TABLE TB_QESTNR_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_QESTNR_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_SJ varchar2(255) ,
  QUSTNR_PURPS varchar2(1000) ,
  QUSTNR_WRITNG_GUIDANCE_CN varchar2(2000) ,
  QUSTNR_TRGET varchar2(1000) ,
  QUSTNR_BGNDE char(20) ,
  QUSTNR_ENDDE char(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_QESTNR_INFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID),
  CONSTRAINT TB_QESTNR_INFO_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID) REFERENCES TB_QUSTNR_TMPLAT (QUSTNR_TMPLAT_ID)
) ;
DROP TABLE TB_QUSTNR_QESITM CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_QESITM (
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTN_SN number(10,0) ,
  QESTN_TY_CODE char(1) ,
  QESTN_CN varchar2(2500) ,
  MXMM_CHOISE_CO number(5,0) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID varchar2(20) NOT NULL,
  CONSTRAINT TB_QUSTNR_QESITM_PK PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT TB_QUSTNR_QESITM_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES TB_QESTNR_INFO (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;
DROP TABLE TB_QUSTNR_IEM CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_IEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_IEM_ID varchar2(20) NOT NULL,
  IEM_SN number(5,0) ,
  IEM_CN varchar2(1000) ,
  ETC_ANSWER_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_QUSTNR_IEM_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID),
  CONSTRAINT TB_QUSTNR_IEM_ibfk_1 FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES TB_QUSTNR_QESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;

DROP TABLE TB_QUSTNR_RESPOND_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_RESPOND_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_RESPOND_ID char(20) NOT NULL,
  SEXDSTN_CODE char(1) ,
  OCCP_TY_CODE varchar2(1) ,
  RESPOND_NM varchar2(50) ,
  BRTHDY char(20) ,
  AREA_NO varchar2(4) ,
  MIDDLE_TELNO varchar2(4) ,
  END_TELNO varchar2(4) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_QUSTNR_RESPOND_INFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID),
  CONSTRAINT TB_QUSTNR_RESPOND_INFO_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES TB_QESTNR_INFO (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;
DROP TABLE TB_QUSTNR_RSPNS_RESULT CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_RSPNS_RESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  RESPOND_ANSWER_CN varchar2(1000) ,
  ETC_ANSWER_CN varchar2(1000) ,
  RESPOND_NM varchar2(50) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  QUSTNR_IEM_ID varchar2(20) ,
  CONSTRAINT TB_QUSTNR_RSPNS_RESULT_PK PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT TB_QUSTNR_RSPNS_RESULT_ibfk_1 FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES TB_QUSTNR_QESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;
DROP TABLE TB_STPLAT_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID char(20) NOT NULL,
  USE_STPLAT_NM varchar2(100) ,
  USE_STPLAT_CN CLOB,
  INFO_PROVD_AGRE_CN CLOB,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_STPLAT_INFO_PK PRIMARY KEY (USE_STPLAT_ID)
) ;

CREATE OR REPLACE VIEW VW_USER_MASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_GNRL_MBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM TB_EMPLYR_INFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_ENTRPRS_MBER
;

-- ============================================================
-- HSQL 정본 파리티 보강 (Altibase native dialect)
-- ============================================================

-- ID 채번 시퀀스 (COMTECOPSEQ)
DROP TABLE COMTECOPSEQ CASCADE CONSTRAINTS;
CREATE TABLE COMTECOPSEQ (
  TABLE_NAME varchar2(20) DEFAULT '' NOT NULL,
  NEXT_ID number(30,0) DEFAULT 0 NOT NULL ,
  CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
) ;

-- 일정 정보 (TB_SCHDUL_INFO)
DROP TABLE TB_SCHDUL_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_SCHDUL_INFO (
  SCHDUL_ID char(20) NOT NULL,
  SCHDUL_SE char(1) ,
  SCHDUL_DEPT_ID varchar2(20) ,
  SCHDUL_KND_CODE varchar2(20) ,
  SCHDUL_BEGINDE DATE ,
  SCHDUL_ENDDE DATE ,
  SCHDUL_NM varchar2(255) ,
  SCHDUL_CN varchar2(2500) ,
  SCHDUL_PLACE varchar2(255) ,
  SCHDUL_IPCR_CODE char(1) ,
  SCHDUL_CHARGER_ID varchar2(20) ,
  ATCH_FILE_ID char(20) ,
  REPTIT_SE_CODE char(3) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_SCHDUL_INFO_PK PRIMARY KEY (SCHDUL_ID)
) ;

-- 휴일 정보 (TB_RESTDE)
DROP TABLE TB_RESTDE CASCADE CONSTRAINTS;
CREATE TABLE TB_RESTDE (
  RESTDE_NO number(20,0) NOT NULL,
  RESTDE_DE char(8) NOT NULL,
  RESTDE_NM varchar2(100) NOT NULL,
  RESTDE_DC varchar2(200) ,
  RESTDE_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_RESTDE_PK PRIMARY KEY (RESTDE_NO)
) ;

-- 업무사용자 정보 변경내역 (TB_EMPLYR_INFO_CHNG_DTLS) : FK -> TB_EMPLYR_INFO
DROP TABLE TB_EMPLYR_INFO_CHNG_DTLS CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_INFO_CHNG_DTLS (
  EMPLYR_ID varchar2(20) NOT NULL,
  CHANGE_DE char(20) NOT NULL,
  ORGNZT_ID char(20) ,
  GROUP_ID char(20) ,
  EMPL_NO varchar2(20) NOT NULL,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar2(20) ,
  HOUSE_ADRES varchar2(100) NOT NULL,
  HOUSE_END_TELNO varchar2(4) ,
  AREA_NO varchar2(4) ,
  DETAIL_ADRES varchar2(100) NOT NULL,
  ZIP varchar2(6) NOT NULL,
  OFFM_TELNO varchar2(20) ,
  MBTLNUM varchar2(20) NOT NULL,
  EMAIL_ADRES varchar2(50) ,
  HOUSE_MIDDLE_TELNO varchar2(4) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar2(15) NOT NULL,
  ESNTL_ID char(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_PK PRIMARY KEY (EMPLYR_ID,CHANGE_DE),
  CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_ibfk_1 FOREIGN KEY (EMPLYR_ID) REFERENCES TB_EMPLYR_INFO (EMPLYR_ID)
) ;