-- 개정이력: 2026.06.17  구재호  전 DBMS TB_ 표준 명명 현행화
DROP TABLE IDS CASCADE CONSTRAINTS;
CREATE TABLE IDS  (
  TABLE_NAME varchar2(20) NOT NULL,  -- 대상 테이블명
  NEXT_ID number(30,0)DEFAULT 0 NOT NULL,  -- 다음 ID 값
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
DROP TABLE TB_CMMN_CL_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_CL_CODE (
  CL_CODE char(3) NOT NULL,  -- 분류코드
  CL_CODE_NM varchar2(60),  -- 분류코드명
  CL_CODE_DC varchar2(200),  -- 분류코드 설명
  USE_AT char(1),  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_CMMN_CL_CODE_PK PRIMARY KEY (CL_CODE)
) ;
DROP TABLE TB_CMMN_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_CODE (
  CODE_ID varchar2(6) NOT NULL,  -- 코드ID
  CODE_ID_NM varchar2(60),  -- 코드ID명
  CODE_ID_DC varchar2(200),  -- 코드ID 설명
  USE_AT char(1),  -- 사용여부(Y/N)
  CL_CODE char(3),  -- 분류코드
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_CMMN_CODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT TB_CMMN_CODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES TB_CMMN_CL_CODE (CL_CODE)
) ;
DROP TABLE TB_CMMN_DETAIL_CODE CASCADE CONSTRAINTS;
CREATE TABLE TB_CMMN_DETAIL_CODE (
  CODE_ID varchar2(6) NOT NULL,  -- 코드ID
  CODE varchar2(15) NOT NULL,  -- 상세코드
  CODE_NM varchar2(60),  -- 상세코드명
  CODE_DC varchar2(200),  -- 상세코드 설명
  USE_AT char(1),  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_CMMN_DETAIL_CODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT TB_CMMN_DETAIL_CODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES TB_CMMN_CODE (CODE_ID)
) ;
DROP TABLE TB_ORGNZT_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_ORGNZT_INFO (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,  -- 조직ID
  ORGNZT_NM varchar2(20) NOT NULL,  -- 조직명
  ORGNZT_DC varchar2(100),  -- 조직 설명
  CONSTRAINT TB_ORGNZT_INFO_PK PRIMARY KEY (ORGNZT_ID)
) ;
DROP TABLE TB_AUTHOR_GROUP_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_AUTHOR_GROUP_INFO (
  GROUP_ID char(20) DEFAULT '' NOT NULL,  -- 그룹ID
  GROUP_NM varchar2(60) NOT NULL,  -- 그룹명
  GROUP_CREAT_DE char(20) NOT NULL,  -- 생성일자
  GROUP_DC varchar2(100),  -- 그룹 설명
  CONSTRAINT TB_AUTHOR_GROUP_INFO_PK PRIMARY KEY (GROUP_ID)
) ;
DROP TABLE TB_AUTHOR_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_AUTHOR_INFO (
  AUTHOR_CODE varchar2(30) DEFAULT '' NOT NULL,  -- 권한코드
  AUTHOR_NM varchar2(60) NOT NULL,  -- 권한명
  AUTHOR_DC varchar2(200),  -- 권한 설명
  AUTHOR_CREAT_DE char(20) NOT NULL,  -- 생성일자
  CONSTRAINT TB_AUTHOR_INFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;
DROP TABLE TB_ROLES_HIERARCHY CASCADE CONSTRAINTS;
CREATE TABLE TB_ROLES_HIERARCHY (
  PARNTS_ROLE varchar2(30) NOT NULL,  -- 부모롤
  CHLDRN_ROLE varchar2(30) NOT NULL,  -- 자식롤
  CONSTRAINT TB_ROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT TB_ROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT TB_ROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE
) ;
DROP TABLE TB_ROLE_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_ROLE_INFO (
  ROLE_CODE varchar2(50) DEFAULT '' NOT NULL,  -- 역할코드
  ROLE_NM varchar2(60) NOT NULL,  -- 역할명
  ROLE_PTTRN varchar2(300),  -- 롤PTTRN
  ROLE_DC varchar2(200),  -- 역할설명
  ROLE_TY varchar2(80),  -- 역할유형
  ROLE_SORT varchar2(10),  -- 역할정렬
  ROLE_CREAT_DE char(20) NOT NULL,  -- 롤생성일자
  CONSTRAINT TB_ROLE_INFO_PK PRIMARY KEY (ROLE_CODE)
) ;
DROP TABLE TB_AUTHOR_ROLE_RELATE CASCADE CONSTRAINTS;
CREATE TABLE TB_AUTHOR_ROLE_RELATE (
  AUTHOR_CODE varchar2(30) NOT NULL,  -- 권한코드
  ROLE_CODE varchar2(50) NOT NULL,  -- 역할코드
  CREAT_DT DATE,  -- 생성시각
  CONSTRAINT TB_AUTHOR_ROLE_RELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT TB_AUTHOR_ROLE_RELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES TB_ROLE_INFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT TB_AUTHOR_ROLE_RELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE) ON DELETE CASCADE
) ;
DROP TABLE TB_GNRL_MBER CASCADE CONSTRAINTS;
CREATE TABLE TB_GNRL_MBER (
  MBER_ID varchar2(20) DEFAULT '' NOT NULL,  -- 회원ID
  PASSWORD varchar2(200) NOT NULL,  -- 비밀번호(해시)
  PASSWORD_HINT varchar2(100) NOT NULL,  -- 비밀번호 힌트
  PASSWORD_CNSR varchar2(100) NOT NULL,  -- 비밀번호 정답
  IHIDNUM varchar2(200),  -- 주민등록번호
  MBER_NM varchar2(50) NOT NULL,  -- 회원명
  ZIP varchar2(6),  -- 우편번호
  ADRES varchar2(100),  -- 주소
  AREA_NO varchar2(4),  -- 지역번호
  MBER_STTUS varchar2(15),  -- 회원상태코드
  DETAIL_ADRES varchar2(100),  -- 상세주소
  END_TELNO varchar2(4),  -- 전화 끝번호
  MBTLNUM varchar2(20),  -- 휴대전화
  GROUP_ID char(20),  -- 그룹ID
  MBER_FXNUM varchar2(20),  -- 팩스번호
  MBER_EMAIL_ADRES varchar2(50),  -- 이메일주소
  MIDDLE_TELNO varchar2(4),  -- 전화 중간번호
  SBSCRB_DE DATE,  -- 가입일시
  SEXDSTN_CODE char(1),  -- 성별코드
  ESNTL_ID char(20) NOT NULL,  -- 고유ID
  CONSTRAINT TB_GNRL_MBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT TB_GNRL_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_EMPLYR_SCRTY_ESTBS CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_SCRTY_ESTBS (
  SCRTY_DTRMN_TRGET_ID varchar2(20) NOT NULL,  -- 보안결정대상ID(보통 사용자ID)
  MBER_TY_CODE varchar2(15),  -- 회원유형코드
  AUTHOR_CODE varchar2(30) NOT NULL,  -- 권한코드
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT TB_EMPLYR_SCRTY_ESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE)
) ;
DROP TABLE TB_TMPLAT_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_TMPLAT_INFO (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,  -- 템플릿ID
  TMPLAT_NM varchar2(255),  -- 템플릿명
  TMPLAT_COURS varchar2(2000),  -- 템플릿COURS
  USE_AT char(1),  -- 사용여부(Y/N)
  TMPLAT_SE_CODE char(6),  -- 템플릿구분상세코드
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  CONSTRAINT TB_TMPLAT_INFO_PK PRIMARY KEY (TMPLAT_ID)
) ;
DROP TABLE TB_BBS_MASTER CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_MASTER (
  BBS_ID char(20) NOT NULL,  -- 게시판ID
  BBS_NM varchar2(255) NOT NULL,  -- 게시판명
  BBS_INTRCN varchar2(2400),  -- 게시판 소개
  BBS_TY_CODE char(6) NOT NULL,  -- 게시판 유형코드
  BBS_ATTRB_CODE char(6) NOT NULL,  -- 게시판 속성코드
  REPLY_POSBL_AT char(1),  -- 답글 가능(Y/N)
  FILE_ATCH_POSBL_AT char(1) NOT NULL,  -- 파일첨부 가능(Y/N)
  ATCH_POSBL_FILE_NUMBER number(2,0) NOT NULL,  -- 첨부가능 파일 수
  ATCH_POSBL_FILE_SIZE number(8,0),  -- 첨부가능 총 용량(단위: 시스템 정의)
  USE_AT char(1) NOT NULL,  -- 사용여부(Y/N)
  TMPLAT_ID char(20),  -- 템플릿ID
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  FRST_REGIST_PNTTM DATE NOT NULL,  -- 최초등록시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  CONSTRAINT TB_BBS_MASTER_PK PRIMARY KEY (BBS_ID)
) ;
DROP TABLE TB_BBS_USE CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_USE (
  BBS_ID char(20) NOT NULL,  -- 게시판ID
  TRGET_ID char(20) DEFAULT '' NOT NULL,  -- 사용대상ID
  USE_AT char(1) NOT NULL,  -- 사용여부(Y/N)
  REGIST_SE_CODE char(6),  -- 등록구분코드
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_BBS_USE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT TB_BBS_USE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;
DROP TABLE TB_BBS CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS (
  NTT_ID number(20,0) NOT NULL,  -- 게시물ID
  BBS_ID char(20) NOT NULL,  -- 게시판ID
  NTT_NO number(20,0),  -- 게시물 번호(정렬/표시용)
  NTT_SJ varchar2(2000),  -- 제목
  NTT_CN CLOB,  -- 내용
  ANSWER_AT char(1),  -- 답변글 여부(Y/N)
  PARNTSCTT_NO number(10,0),  -- 부모글 번호
  ANSWER_LC number(8),  -- 답변 계층(레벨)
  SORT_ORDR number(8,0),  -- 정렬순서
  RDCNT number(10,0),  -- 조회수
  USE_AT char(1) NOT NULL,  -- 사용여부(Y/N)
  NTCE_BGNDE char(20),  -- 공지 시작일시
  NTCE_ENDDE char(20),  -- 공지 종료일시
  NTCR_ID varchar2(20),  -- 게시자ID
  NTCR_NM varchar2(20),  -- 게시자명
  PASSWORD varchar2(200),  -- 비밀번호(해시)
  ATCH_FILE_ID char(20),  -- 첨부파일 묶음ID
  FRST_REGIST_PNTTM DATE NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_BBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT TB_BBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;
DROP TABLE TB_BBS_MASTER_OPTN CASCADE CONSTRAINTS;
CREATE TABLE TB_BBS_MASTER_OPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,  -- 게시판ID
  ANSWER_AT char(1) DEFAULT '' NOT NULL,  -- 답변글 여부(Y/N)
  STSFDG_AT char(1) DEFAULT '' NOT NULL,  -- 만족도 조사 사용(Y/N)
  FRST_REGIST_PNTTM DATE DEFAULT SYSDATE NOT NULL,  -- 최초등록시각
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  FRST_REGISTER_ID varchar2(20) DEFAULT '' NOT NULL,  -- 최초등록자ID
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_BBS_MASTER_OPTN_PK PRIMARY KEY (BBS_ID)
) ;
DROP TABLE TB_EMPLYR_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_INFO (
  EMPLYR_ID varchar2(20) NOT NULL,  -- 사용자ID
  ORGNZT_ID char(20),  -- 조직ID
  USER_NM varchar2(60) NOT NULL,  -- 사용자명
  PASSWORD varchar2(200) NOT NULL,  -- 비밀번호(해시)
  EMPL_NO varchar2(20),  -- 사번
  IHIDNUM varchar2(200),  -- 주민등록번호
  SEXDSTN_CODE char(1),  -- 성별코드
  BRTHDY char(20),  -- 생년월일
  FXNUM varchar2(20),  -- 팩스
  HOUSE_ADRES varchar2(100),  -- 자택주소
  PASSWORD_HINT varchar2(100) NOT NULL,  -- 비밀번호 힌트
  PASSWORD_CNSR varchar2(100) NOT NULL,  -- 비밀번호 정답
  HOUSE_END_TELNO varchar2(4),  -- 자택전화 끝번호
  AREA_NO varchar2(4),  -- 지역번호
  DETAIL_ADRES varchar2(100),  -- 상세주소
  ZIP varchar2(6),  -- 우편번호
  OFFM_TELNO varchar2(20),  -- 사무실전화
  MBTLNUM varchar2(20),  -- 휴대전화
  EMAIL_ADRES varchar2(50),  -- 이메일
  OFCPS_NM varchar2(60),  -- 직책명
  HOUSE_MIDDLE_TELNO varchar2(4),  -- 자택전화 중간번호
  GROUP_ID char(20),  -- 그룹ID
  PSTINST_CODE char(8),  -- 소속기관코드
  EMPLYR_STTUS_CODE varchar2(15) NOT NULL,  -- 사용자상태코드
  ESNTL_ID char(20) NOT NULL,  -- 고유ID
  CRTFC_DN_VALUE varchar2(20),  -- 인증DN
  SBSCRB_DE DATE,  -- 가입일시
  CONSTRAINT TB_EMPLYR_INFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT TB_EMPLYR_INFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT TB_EMPLYR_INFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES TB_ORGNZT_INFO (ORGNZT_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_ZIP CASCADE CONSTRAINTS;
CREATE TABLE TB_ZIP (
  ZIP varchar2(6) NOT NULL,  -- 우편번호
  SN number(10,0) DEFAULT '0' NOT NULL,  -- 일련번호
  CTPRVN_NM varchar2(20),  -- 시도명
  SIGNGU_NM varchar2(20),  -- 시군구명
  EMD_NM varchar2(60),  -- 읍면동명
  LI_BULD_NM varchar2(60),  -- 리건물명
  LNBR_DONG_HO varchar2(20),  -- 지번동호
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_ZIP_PK PRIMARY KEY (ZIP,SN)
) ;
DROP TABLE TB_BANNER CASCADE CONSTRAINTS;
CREATE TABLE TB_BANNER (
  BANNER_ID char(20) DEFAULT '' NOT NULL,  -- 배너ID
  BANNER_NM varchar2(60) NOT NULL,  -- 배너명
  LINK_URL varchar2(255) NOT NULL,  -- 연계URL
  BANNER_IMAGE varchar2(60) NOT NULL,  -- 배너이미지
  BANNER_DC varchar2(200),  -- 배너설명
  REFLCT_AT char(1) NOT NULL,  -- REFLCT여부
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  BANNER_IMAGE_FILE varchar2(60),  -- 배너이미지파일
  SORT_ORDR number(8,0),  -- 정렬순서
  BANNER_TY varchar(10) DEFAULT 'MAIN',  -- 배너유형
  POPUP_LEFT number(8,0),  -- 팝업LEFT
  POPUP_TOP number(8,0),  -- 팝업TOP
  POPUP_WIDTH number(8,0),  -- 팝업너비
  POPUP_HEIGHT number(8,0),  -- 팝업HEIGHT
  POPUP_GROUP_AT char(1) DEFAULT 'N',  -- 팝업그룹여부
  EXPSR_BGNDE DATE,  -- 노출시작일자
  EXPSR_ENDDE DATE,  -- 노출종료일자
  CONSTRAINT TB_BANNER_PK PRIMARY KEY (BANNER_ID)
) ;
DROP TABLE TB_ENTRPRS_MBER CASCADE CONSTRAINTS;
CREATE TABLE TB_ENTRPRS_MBER (
  ENTRPRS_MBER_ID varchar2(20) DEFAULT '' NOT NULL,  -- 기업회원ID
  ENTRPRS_SE_CODE char(15),  -- 기업구분코드
  BIZRNO varchar2(10),  -- 사업자등록번호
  JURIRNO varchar2(13),  -- 법인등록번호
  CMPNY_NM varchar2(60) NOT NULL,  -- 회사명
  CXFC varchar2(50),  -- 대표자명
  ZIP varchar2(6),  -- 우편번호
  ADRES varchar2(100),  -- 주소
  ENTRPRS_MIDDLE_TELNO varchar2(4),  -- 전화 중간번호
  FXNUM varchar2(20),  -- 팩스
  INDUTY_CODE char(15),  -- 업종코드
  APPLCNT_NM varchar2(50),  -- 신청자명
  APPLCNT_IHIDNUM varchar2(200),  -- 신청자 주민등록번호
  SBSCRB_DE DATE,  -- 가입일시
  ENTRPRS_MBER_STTUS varchar2(15),  -- 회원상태코드
  ENTRPRS_MBER_PASSWORD varchar2(200) NOT NULL,  -- 비밀번호(해시)
  ENTRPRS_MBER_PASSWORD_HINT varchar2(100) NOT NULL,  -- 비밀번호 힌트
  ENTRPRS_MBER_PASSWORD_CNSR varchar2(100) NOT NULL,  -- 비밀번호 정답
  GROUP_ID char(20),  -- 그룹ID
  DETAIL_ADRES varchar2(100),  -- 상세주소
  ENTRPRS_END_TELNO varchar2(4),  -- 전화 끝번호
  AREA_NO varchar2(4),  -- 지역번호
  APPLCNT_EMAIL_ADRES varchar2(50),  -- 신청자 이메일
  ESNTL_ID char(20) NOT NULL,  -- 고유ID
  CONSTRAINT TB_ENTRPRS_MBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT TB_ENTRPRS_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;
DROP TABLE TB_FILE CASCADE CONSTRAINTS;
CREATE TABLE TB_FILE (
  ATCH_FILE_ID char(20) NOT NULL,  -- 첨부파일 묶음ID
  CREAT_DT DATE NOT NULL,  -- 생성시각
  USE_AT char(1),  -- 사용여부(Y/N)
  CONSTRAINT TB_FILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;
DROP TABLE TB_FILE_DETAIL CASCADE CONSTRAINTS;
CREATE TABLE TB_FILE_DETAIL (
  ATCH_FILE_ID char(20) NOT NULL,  -- 첨부파일 묶음ID
  FILE_SN number(10,0) NOT NULL,  -- 파일 일련번호
  FILE_STRE_COURS varchar2(2000) NOT NULL,  -- 파일 저장경로
  STRE_FILE_NM varchar2(255) NOT NULL,  -- 저장파일명
  ORIGNL_FILE_NM varchar2(255),  -- 원파일명
  FILE_EXTSN varchar2(20) NOT NULL,  -- 파일확장자
  FILE_CN CLOB,  -- 파일 내용/비고
  FILE_SIZE number(8,0),  -- 파일크기(Byte)
  CONSTRAINT TB_FILE_DETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT TB_FILE_DETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE (ATCH_FILE_ID)
) ;
DROP TABLE TB_FAQ_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_FAQ_INFO (
  FAQ_ID char(20) NOT NULL,  -- FAQID
  QESTN_SJ varchar2(255),  -- 질문제목
  QESTN_CN varchar2(2500),  -- 질문내용
  ANSWER_CN varchar2(2500),  -- 답변내용
  RDCNT number(10,0),  -- 조회수
  FRST_REGIST_PNTTM DATE NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE NOT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20) NOT NULL,  -- 최종수정자ID
  ATCH_FILE_ID char(20),  -- 첨부파일 묶음ID
  QNA_PROCESS_STTUS_CODE char(1),  -- 질의응답처리상태상세코드
  CONSTRAINT TB_FAQ_INFO_PK PRIMARY KEY (FAQ_ID),
  CONSTRAINT TB_FAQ_INFO_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE (ATCH_FILE_ID)
) ;
DROP TABLE TB_INDVDL_INFO_POLICY CASCADE CONSTRAINTS;
CREATE TABLE TB_INDVDL_INFO_POLICY (
  INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,  -- 개인정보정책ID
  INDVDL_INFO_POLICY_CN varchar2(2500),  -- 개인정보정책내용
  INDVDL_INFO_POLICY_AGRE_AT char(1),  -- 개인정보정책동의여부
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  INDVDL_INFO_POLICY_NM varchar2(255),  -- 개인정보정책명
  VER varchar2(20),  -- 버전
  APLC_DE varchar2(8),  -- 응용일자
  REPRSNT_AT char(1) DEFAULT 'N',  -- REPRSNT여부
  CONSTRAINT TB_INDVDL_INFO_POLICY_PK PRIMARY KEY (INDVDL_INFO_POLICY_ID)
) ;
DROP TABLE TB_PROGRM_LIST CASCADE CONSTRAINTS;
CREATE TABLE TB_PROGRM_LIST (
  PROGRM_FILE_NM varchar2(60) DEFAULT '' NOT NULL,  -- 프로그램파일명
  PROGRM_STRE_PATH varchar2(100) NOT NULL,  -- 프로그램STRE경로
  PROGRM_KOREAN_NM varchar2(60),  -- 프로그램KOREAN명
  PROGRM_DC varchar2(200),  -- 프로그램설명
  URL varchar2(100) NOT NULL,  -- URL
  CONSTRAINT TB_PROGRM_LIST_PK PRIMARY KEY (PROGRM_FILE_NM)
) ;
DROP TABLE TB_MENU_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_MENU_INFO (
  MENU_NM varchar2(60) NOT NULL,  -- 메뉴명
  PROGRM_FILE_NM varchar2(60) NOT NULL,  -- 프로그램파일명
  MENU_NO number(20,0) NOT NULL,  -- 메뉴번호
  UPPER_MENU_NO number(20,0),  -- UPPER메뉴번호
  MENU_ORDR number(5,0) NOT NULL,  -- 메뉴순서
  MENU_DC varchar2(250),  -- 메뉴설명
  RELATE_IMAGE_PATH varchar2(100),  -- 관련이미지경로
  RELATE_IMAGE_NM varchar2(60),  -- 관련이미지명
  CONSTRAINT TB_MENU_INFO_PK PRIMARY KEY (MENU_NO),
  CONSTRAINT TB_MENU_INFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES TB_MENU_INFO (MENU_NO),
  CONSTRAINT TB_MENU_INFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES TB_PROGRM_LIST (PROGRM_FILE_NM) ON DELETE CASCADE
) ;
DROP TABLE TB_MENU_CREAT_DTLS CASCADE CONSTRAINTS;
CREATE TABLE TB_MENU_CREAT_DTLS (
  MENU_NO number(20,0) NOT NULL,  -- 메뉴번호
  AUTHOR_CODE varchar2(30) NOT NULL,  -- 권한코드
  MAPNG_CREAT_ID varchar2(30),  -- MAPNG생성ID
  CONSTRAINT TB_MENU_CREAT_DTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT TB_MENU_CREAT_DTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO (AUTHOR_CODE),
  CONSTRAINT TB_MENU_CREAT_DTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES TB_MENU_INFO (MENU_NO) ON DELETE CASCADE
) ;
DROP TABLE TB_QA_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_QA_INFO (
  QA_ID char(20) NOT NULL,  -- 질의응답ID
  QESTN_SJ varchar2(255),  -- 질문제목
  QESTN_CN varchar2(2500),  -- 질문내용
  WRITNG_DE char(20),  -- 작성일자
  RDCNT number(10,0),  -- 조회수
  EMAIL_ADRES varchar2(50),  -- 이메일
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  QNA_PROCESS_STTUS_CODE char(1),  -- 질의응답처리상태상세코드
  WRTER_NM varchar2(20),  -- WRTER명
  ANSWER_CN varchar2(2500),  -- 답변내용
  WRITNG_PASSWORD varchar2(20),  -- 작성비밀번호(해시)
  ANSWER_DE char(20),  -- 답변일자
  EMAIL_ANSWER_AT char(1),  -- 이메일답변여부
  AREA_NO varchar2(4),  -- 지역번호
  MIDDLE_TELNO varchar2(4),  -- 전화 중간번호
  END_TELNO varchar2(4),  -- 전화 끝번호
  CONSTRAINT TB_QA_INFO_PK PRIMARY KEY (QA_ID)
) ;

DROP TABLE TB_QUSTNR_TMPLAT CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_TMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QUSTNR_TMPLAT_TY varchar2(100),  -- 설문템플릿유형
  QUSTNR_TMPLAT_DC varchar2(2000),  -- 설문템플릿설명
  QUSTNR_TMPLAT_PATH_NM varchar2(100),  -- 설문템플릿경로명
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  QUSTNR_TMPLAT_IMAGE_INFO blob,  -- 설문템플릿이미지정보
  CONSTRAINT TB_QUSTNR_TMPLAT_PK PRIMARY KEY (QUSTNR_TMPLAT_ID)
) ;

DROP TABLE TB_QESTNR_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_QESTNR_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_SJ varchar2(255),  -- 설문제목
  QUSTNR_PURPS varchar2(1000),  -- 설문목적
  QUSTNR_WRITNG_GUIDANCE_CN varchar2(2000),  -- 설문작성안내내용
  QUSTNR_TRGET varchar2(1000),  -- 설문대상
  QUSTNR_BGNDE char(20),  -- 설문시작일자
  QUSTNR_ENDDE char(20),  -- 설문종료일자
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_QESTNR_INFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID),
  CONSTRAINT TB_QESTNR_INFO_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID) REFERENCES TB_QUSTNR_TMPLAT (QUSTNR_TMPLAT_ID)
) ;
DROP TABLE TB_QUSTNR_QESITM CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_QESITM (
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTN_SN number(10,0),  -- 질문일련번호
  QESTN_TY_CODE char(1),  -- 질문유형상세코드
  QESTN_CN varchar2(2500),  -- 질문내용
  MXMM_CHOISE_CO number(5,0),  -- MXMMCHOISE수
  FRST_REGIST_PNTTM DATE NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE NOT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20) NOT NULL,  -- 최종수정자ID
  CONSTRAINT TB_QUSTNR_QESITM_PK PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT TB_QUSTNR_QESITM_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES TB_QESTNR_INFO (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;
DROP TABLE TB_QUSTNR_IEM CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_IEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_IEM_ID varchar2(20) NOT NULL,  -- 설문항목ID
  IEM_SN number(5,0),  -- 항목일련번호
  IEM_CN varchar2(1000),  -- 항목내용
  ETC_ANSWER_AT char(1),  -- 기타답변여부
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_QUSTNR_IEM_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID),
  CONSTRAINT TB_QUSTNR_IEM_ibfk_1 FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES TB_QUSTNR_QESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;

DROP TABLE TB_QUSTNR_RESPOND_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_RESPOND_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_RESPOND_ID char(20) NOT NULL,  -- 설문응답ID
  SEXDSTN_CODE char(1),  -- 성별코드
  OCCP_TY_CODE varchar2(10),  -- 직업유형상세코드
  RESPOND_NM varchar2(50),  -- 응답명
  BRTHDY char(20),  -- 생년월일
  AREA_NO varchar2(4),  -- 지역번호
  MIDDLE_TELNO varchar2(4),  -- 전화 중간번호
  END_TELNO varchar2(4),  -- 전화 끝번호
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_QUSTNR_RESPOND_INFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID),
  CONSTRAINT TB_QUSTNR_RESPOND_INFO_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES TB_QESTNR_INFO (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;
DROP TABLE TB_QUSTNR_RSPNS_RESULT CASCADE CONSTRAINTS;
CREATE TABLE TB_QUSTNR_RSPNS_RESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,  -- 설문응답결과ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  RESPOND_ANSWER_CN varchar2(1000),  -- 응답답변내용
  ETC_ANSWER_CN varchar2(1000),  -- 기타답변내용
  RESPOND_NM varchar2(50),  -- 응답명
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  QUSTNR_IEM_ID varchar2(20),  -- 설문항목ID
  CONSTRAINT TB_QUSTNR_RSPNS_RESULT_PK PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT TB_QUSTNR_RSPNS_RESULT_ibfk_1 FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES TB_QUSTNR_QESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;
DROP TABLE TB_STPLAT_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID char(20) NOT NULL,  -- 이용약관ID
  USE_STPLAT_NM varchar2(100),  -- 이용약관명
  USE_STPLAT_CN CLOB,  -- 이용약관 내용
  INFO_PROVD_AGRE_CN CLOB,  -- 정보제공 동의 내용
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  VER varchar2(20),  -- 버전
  APLC_DE varchar2(8),  -- 응용일자
  REPRSNT_AT char(1) DEFAULT 'N',  -- REPRSNT여부
  CONSTRAINT TB_STPLAT_INFO_PK PRIMARY KEY (USE_STPLAT_ID)
) ;

CREATE OR REPLACE VIEW VW_USER_MASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_GNRL_MBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM TB_EMPLYR_INFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM TB_ENTRPRS_MBER
;

-- ============================================================
-- HSQL 정본 파리티 보강 (Altibase native dialect)
-- ============================================================

-- ID 채번 시퀀스 (COMTECOPSEQ)
DROP TABLE COMTECOPSEQ CASCADE CONSTRAINTS;
CREATE TABLE COMTECOPSEQ (
  TABLE_NAME varchar2(20) DEFAULT '' NOT NULL,  -- 대상 테이블명
  NEXT_ID number(30,0) DEFAULT 0 NOT NULL,  -- 다음 ID 값
  CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
) ;

-- 일정 정보 (TB_SCHDUL_INFO)
DROP TABLE TB_SCHDUL_INFO CASCADE CONSTRAINTS;
CREATE TABLE TB_SCHDUL_INFO (
  SCHDUL_ID char(20) NOT NULL,  -- 일정ID
  SCHDUL_SE char(1),  -- 일정구분코드
  SCHDUL_DEPT_ID varchar2(20),  -- 부서ID
  SCHDUL_KND_CODE varchar2(20),  -- 일정종류코드
  SCHDUL_BEGINDE DATE,  -- 시작일시
  SCHDUL_ENDDE DATE,  -- 종료일시
  SCHDUL_NM varchar2(255),  -- 일정명
  SCHDUL_CN varchar2(2500),  -- 일정 내용
  SCHDUL_PLACE varchar2(255),  -- 장소
  SCHDUL_IPCR_CODE char(1),  -- 중요도코드
  SCHDUL_CHARGER_ID varchar2(20),  -- 담당자ID
  ATCH_FILE_ID char(20),  -- 첨부파일 묶음ID
  REPTIT_SE_CODE char(3),  -- 반복구분코드
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_SCHDUL_INFO_PK PRIMARY KEY (SCHDUL_ID)
) ;

-- 휴일 정보 (TB_RESTDE)
DROP TABLE TB_RESTDE CASCADE CONSTRAINTS;
CREATE TABLE TB_RESTDE (
  RESTDE_NO number(20,0) NOT NULL,  -- 휴일번호
  RESTDE_DE char(8) NOT NULL,  -- 휴일일자
  RESTDE_NM varchar2(100) NOT NULL,  -- 휴일명
  RESTDE_DC varchar2(200),  -- 휴일설명
  RESTDE_SE_CODE char(6),  -- 휴일구분상세코드
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_RESTDE_PK PRIMARY KEY (RESTDE_NO)
) ;

-- 업무사용자 정보 변경내역 (TB_EMPLYR_INFO_CHNG_DTLS) : FK -> TB_EMPLYR_INFO
DROP TABLE TB_EMPLYR_INFO_CHNG_DTLS CASCADE CONSTRAINTS;
CREATE TABLE TB_EMPLYR_INFO_CHNG_DTLS (
  EMPLYR_ID varchar2(20) NOT NULL,  -- 사용자ID
  CHANGE_DE char(20) NOT NULL,  -- 변경일자
  ORGNZT_ID char(20),  -- 조직ID
  GROUP_ID char(20),  -- 그룹ID
  EMPL_NO varchar2(20) NOT NULL,  -- 사번
  SEXDSTN_CODE char(1),  -- 성별코드
  BRTHDY char(20),  -- 생년월일
  FXNUM varchar2(20),  -- 팩스
  HOUSE_ADRES varchar2(100) NOT NULL,  -- 자택주소
  HOUSE_END_TELNO varchar2(4),  -- 자택전화 끝번호
  AREA_NO varchar2(4),  -- 지역번호
  DETAIL_ADRES varchar2(100) NOT NULL,  -- 상세주소
  ZIP varchar2(6) NOT NULL,  -- 우편번호
  OFFM_TELNO varchar2(20),  -- 사무실전화
  MBTLNUM varchar2(20) NOT NULL,  -- 휴대전화
  EMAIL_ADRES varchar2(50),  -- 이메일
  HOUSE_MIDDLE_TELNO varchar2(4),  -- 자택전화 중간번호
  PSTINST_CODE char(8),  -- 소속기관코드
  EMPLYR_STTUS_CODE varchar2(15) NOT NULL,  -- 사용자상태코드
  ESNTL_ID char(20),  -- 고유ID
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_PK PRIMARY KEY (EMPLYR_ID,CHANGE_DE),
  CONSTRAINT TB_EMPLYR_INFO_CHNG_DTLS_ibfk_1 FOREIGN KEY (EMPLYR_ID) REFERENCES TB_EMPLYR_INFO (EMPLYR_ID)
) ;