-- 개정이력: 2026.06.17  구재호  전 DBMS TB_ 표준 명명 현행화
-- ============================================================
-- portal-site-boot PostgreSQL DDL (shtdb.sql HSQL 정본에서 생성)
-- 명명규칙: TB_ + snake_case / 감사컬럼 4종
-- 사용: psql -U postgres -d pst -f all_pst_ddl_postgresql.sql
-- ============================================================

DROP VIEW IF EXISTS VW_USER_MASTER CASCADE;
DROP TABLE IF EXISTS TB_STPLAT_INFO CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_RSPNS_RESULT CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_RESPOND_INFO CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_IEM CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_QESITM CASCADE;
DROP TABLE IF EXISTS TB_QESTNR_INFO CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_TMPLAT CASCADE;
DROP TABLE IF EXISTS TB_MENU_CREAT_DTLS CASCADE;
DROP TABLE IF EXISTS TB_MENU_INFO CASCADE;
DROP TABLE IF EXISTS TB_PROGRM_LIST CASCADE;
DROP TABLE IF EXISTS TB_INDVDL_INFO_POLICY CASCADE;
DROP TABLE IF EXISTS TB_BANNER CASCADE;
DROP TABLE IF EXISTS TB_ZIP CASCADE;
DROP TABLE IF EXISTS TB_AUTHOR_ROLE_RELATE CASCADE;
DROP TABLE IF EXISTS TB_ROLE_INFO CASCADE;
DROP TABLE IF EXISTS TB_ROLES_HIERARCHY CASCADE;
DROP TABLE IF EXISTS TB_TMPLAT_INFO CASCADE;
DROP TABLE IF EXISTS TB_QA_INFO CASCADE;
DROP TABLE IF EXISTS TB_FAQ_INFO CASCADE;
DROP TABLE IF EXISTS TB_RESTDE CASCADE;
DROP TABLE IF EXISTS TB_SCHDUL_INFO CASCADE;
DROP TABLE IF EXISTS TB_FILE_DETAIL CASCADE;
DROP TABLE IF EXISTS TB_FILE CASCADE;
DROP TABLE IF EXISTS TB_BBS CASCADE;
DROP TABLE IF EXISTS TB_BBS_USE CASCADE;
DROP TABLE IF EXISTS TB_BBS_MASTER_OPTN CASCADE;
DROP TABLE IF EXISTS TB_BBS_MASTER CASCADE;
DROP TABLE IF EXISTS TB_ENTRPRS_MBER CASCADE;
DROP TABLE IF EXISTS TB_GNRL_MBER CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_SCRTY_ESTBS CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_INFO_CHNG_DTLS CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_INFO CASCADE;
DROP TABLE IF EXISTS TB_ORGNZT_INFO CASCADE;
DROP TABLE IF EXISTS TB_AUTHOR_GROUP_INFO CASCADE;
DROP TABLE IF EXISTS TB_AUTHOR_INFO CASCADE;
DROP TABLE IF EXISTS TB_CMMN_DETAIL_CODE CASCADE;
DROP TABLE IF EXISTS TB_CMMN_CODE CASCADE;
DROP TABLE IF EXISTS TB_CMMN_CL_CODE CASCADE;
DROP TABLE IF EXISTS COMTECOPSEQ CASCADE;
DROP TABLE IF EXISTS IDS CASCADE;

CREATE TABLE IDS (
  TABLE_NAME VARCHAR(20) DEFAULT '' NOT NULL PRIMARY KEY,  -- 대상 테이블명
  NEXT_ID NUMERIC(30) DEFAULT 0 NOT NULL  -- 다음 ID 값
);
CREATE TABLE COMTECOPSEQ (
  TABLE_NAME VARCHAR(20) DEFAULT '' NOT NULL PRIMARY KEY,  -- 대상 테이블명
  NEXT_ID NUMERIC(30) DEFAULT 0 NOT NULL  -- 다음 ID 값
);
CREATE TABLE TB_CMMN_CL_CODE (
  CL_CODE CHAR(3) NOT NULL PRIMARY KEY,  -- 분류코드
  CL_CODE_NM VARCHAR(60),  -- 분류코드명
  CL_CODE_DC VARCHAR(200),  -- 분류코드 설명
  USE_AT CHAR(1),  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_CMMN_CODE (
  CODE_ID VARCHAR(6) NOT NULL PRIMARY KEY,  -- 코드ID
  CODE_ID_NM VARCHAR(60),  -- 코드ID명
  CODE_ID_DC VARCHAR(200),  -- 코드ID 설명
  USE_AT CHAR(1),  -- 사용여부(Y/N)
  CL_CODE CHAR(3),  -- 분류코드
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  CONSTRAINT FK_CMMN_CODE_CL FOREIGN KEY (CL_CODE) REFERENCES TB_CMMN_CL_CODE(CL_CODE)
);
CREATE TABLE TB_CMMN_DETAIL_CODE (
  CODE_ID VARCHAR(6) NOT NULL,  -- 코드ID
  CODE VARCHAR(15) NOT NULL,  -- 상세코드
  CODE_NM VARCHAR(60),  -- 상세코드명
  CODE_DC VARCHAR(200),  -- 상세코드 설명
  USE_AT CHAR(1),  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  PRIMARY KEY(CODE_ID, CODE),
  CONSTRAINT FK_CMMN_DTL_CODE FOREIGN KEY(CODE_ID) REFERENCES TB_CMMN_CODE(CODE_ID)
);
CREATE TABLE TB_AUTHOR_INFO (
  AUTHOR_CODE VARCHAR(30) NOT NULL PRIMARY KEY,  -- 권한코드
  AUTHOR_NM VARCHAR(60) NOT NULL,  -- 권한명
  AUTHOR_DC VARCHAR(200),  -- 권한 설명
  AUTHOR_CREAT_DE CHAR(20) NOT NULL,  -- 생성일자
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_AUTHOR_GROUP_INFO (
  GROUP_ID CHAR(20) DEFAULT '' NOT NULL PRIMARY KEY,  -- 그룹ID
  GROUP_NM VARCHAR(60) NOT NULL,  -- 그룹명
  GROUP_CREAT_DE CHAR(20) NOT NULL,  -- 생성일자
  GROUP_DC VARCHAR(100),  -- 그룹 설명
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_ORGNZT_INFO (
  ORGNZT_ID CHAR(20) DEFAULT '' NOT NULL PRIMARY KEY,  -- 조직ID
  ORGNZT_NM VARCHAR(20) NOT NULL,  -- 조직명
  ORGNZT_DC VARCHAR(100),  -- 조직 설명
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_EMPLYR_INFO (
  EMPLYR_ID VARCHAR(20) NOT NULL PRIMARY KEY,  -- 사용자ID
  ORGNZT_ID CHAR(20),  -- 조직ID
  USER_NM VARCHAR(60) NOT NULL,  -- 사용자명
  PASSWORD VARCHAR(200) NOT NULL,  -- 비밀번호(해시)
  EMPL_NO VARCHAR(20),  -- 사번
  IHIDNUM VARCHAR(13),  -- 주민등록번호
  SEXDSTN_CODE CHAR(1),  -- 성별코드
  BRTHDY CHAR(20),  -- 생년월일
  FXNUM VARCHAR(20),  -- 팩스
  HOUSE_ADRES VARCHAR(100),  -- 자택주소
  PASSWORD_HINT VARCHAR(100) NOT NULL,  -- 비밀번호 힌트
  PASSWORD_CNSR VARCHAR(100) NOT NULL,  -- 비밀번호 정답
  HOUSE_END_TELNO VARCHAR(4),  -- 자택전화 끝번호
  AREA_NO VARCHAR(4),  -- 지역번호
  DETAIL_ADRES VARCHAR(100),  -- 상세주소
  ZIP VARCHAR(6),  -- 우편번호
  OFFM_TELNO VARCHAR(20),  -- 사무실전화
  MBTLNUM VARCHAR(20),  -- 휴대전화
  EMAIL_ADRES VARCHAR(50),  -- 이메일
  OFCPS_NM VARCHAR(60),  -- 직책명
  HOUSE_MIDDLE_TELNO VARCHAR(4),  -- 자택전화 중간번호
  GROUP_ID CHAR(20),  -- 그룹ID
  PSTINST_CODE CHAR(8),  -- 소속기관코드
  EMPLYR_STTUS_CODE VARCHAR(15) NOT NULL,  -- 사용자상태코드
  ESNTL_ID CHAR(20) NOT NULL,  -- 고유ID
  CRTFC_DN_VALUE VARCHAR(20),  -- 인증DN
  SBSCRB_DE TIMESTAMP,  -- 가입일시
  OCCP_TY VARCHAR(10),  -- 직업유형
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  CONSTRAINT FK_EMPLYR_GROUP FOREIGN KEY(GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO(GROUP_ID) ON DELETE CASCADE
);
ALTER TABLE TB_EMPLYR_INFO ADD CONSTRAINT FK_EMPLYR_ORGNZT FOREIGN KEY(ORGNZT_ID) REFERENCES TB_ORGNZT_INFO(ORGNZT_ID);
CREATE TABLE TB_EMPLYR_INFO_CHNG_DTLS (
  EMPLYR_ID VARCHAR(20) NOT NULL,  -- 사용자ID
  CHANGE_DE CHAR(20) NOT NULL,  -- 변경일자
  ORGNZT_ID CHAR(20),  -- 조직ID
  GROUP_ID CHAR(20),  -- 그룹ID
  EMPL_NO VARCHAR(20) NOT NULL,  -- 사번
  SEXDSTN_CODE CHAR(1),  -- 성별코드
  BRTHDY CHAR(20),  -- 생년월일
  FXNUM VARCHAR(20),  -- 팩스
  HOUSE_ADRES VARCHAR(100) NOT NULL,  -- 자택주소
  HOUSE_END_TELNO VARCHAR(4),  -- 자택전화 끝번호
  AREA_NO VARCHAR(4),  -- 지역번호
  DETAIL_ADRES VARCHAR(100) NOT NULL,  -- 상세주소
  ZIP VARCHAR(6) NOT NULL,  -- 우편번호
  OFFM_TELNO VARCHAR(20),  -- 사무실전화
  MBTLNUM VARCHAR(20) NOT NULL,  -- 휴대전화
  EMAIL_ADRES VARCHAR(50),  -- 이메일
  HOUSE_MIDDLE_TELNO VARCHAR(4),  -- 자택전화 중간번호
  PSTINST_CODE CHAR(8),  -- 소속기관코드
  EMPLYR_STTUS_CODE VARCHAR(15) NOT NULL,  -- 사용자상태코드
  ESNTL_ID CHAR(20),  -- 고유ID
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  PRIMARY KEY(EMPLYR_ID, CHANGE_DE),
  CONSTRAINT FK_CHNG_EMPLYR FOREIGN KEY(EMPLYR_ID) REFERENCES TB_EMPLYR_INFO(EMPLYR_ID)
);
CREATE TABLE TB_EMPLYR_SCRTY_ESTBS (
  SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL PRIMARY KEY,  -- 보안결정대상ID(보통 사용자ID)
  MBER_TY_CODE VARCHAR(15),  -- 회원유형코드
  AUTHOR_CODE VARCHAR(30) NOT NULL,  -- 권한코드
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  CONSTRAINT FK_SCRTY_AUTHOR FOREIGN KEY(AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO(AUTHOR_CODE)
);
CREATE TABLE TB_GNRL_MBER (
  MBER_ID VARCHAR(20) DEFAULT '' NOT NULL PRIMARY KEY,  -- 회원ID
  PASSWORD VARCHAR(200) NOT NULL,  -- 비밀번호(해시)
  PASSWORD_HINT VARCHAR(100),  -- 비밀번호 힌트
  PASSWORD_CNSR VARCHAR(100),  -- 비밀번호 정답
  IHIDNUM VARCHAR(13),  -- 주민등록번호
  MBER_NM VARCHAR(50) NOT NULL,  -- 회원명
  ZIP VARCHAR(6),  -- 우편번호
  ADRES VARCHAR(100),  -- 주소
  AREA_NO VARCHAR(4),  -- 지역번호
  MBER_STTUS VARCHAR(15),  -- 회원상태코드
  DETAIL_ADRES VARCHAR(100),  -- 상세주소
  END_TELNO VARCHAR(4),  -- 전화 끝번호
  MBTLNUM VARCHAR(20),  -- 휴대전화
  GROUP_ID CHAR(20),  -- 그룹ID
  MBER_FXNUM VARCHAR(20),  -- 팩스번호
  MBER_EMAIL_ADRES VARCHAR(50),  -- 이메일주소
  MIDDLE_TELNO VARCHAR(4),  -- 전화 중간번호
  TELNO VARCHAR(20),  -- 전화번호
  SBSCRB_DE TIMESTAMP,  -- 가입일시
  SEXDSTN_CODE CHAR(1),  -- 성별코드
  ESNTL_ID CHAR(20) NOT NULL,  -- 고유ID
  OCCP_TY VARCHAR(10),  -- 직업유형
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  CONSTRAINT FK_GNRL_GROUP FOREIGN KEY(GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO(GROUP_ID) ON DELETE CASCADE
);
CREATE TABLE TB_ENTRPRS_MBER (
  ENTRPRS_MBER_ID VARCHAR(20) DEFAULT '' NOT NULL PRIMARY KEY,  -- 기업회원ID
  ENTRPRS_SE_CODE CHAR(15),  -- 기업구분코드
  BIZRNO VARCHAR(10),  -- 사업자등록번호
  JURIRNO VARCHAR(13),  -- 법인등록번호
  CMPNY_NM VARCHAR(60) NOT NULL,  -- 회사명
  CXFC VARCHAR(50),  -- 대표자명
  ZIP VARCHAR(6),  -- 우편번호
  ADRES VARCHAR(100),  -- 주소
  ENTRPRS_MIDDLE_TELNO VARCHAR(4),  -- 전화 중간번호
  FXNUM VARCHAR(20),  -- 팩스
  INDUTY_CODE CHAR(15),  -- 업종코드
  APPLCNT_NM VARCHAR(50) NOT NULL,  -- 신청자명
  APPLCNT_IHIDNUM VARCHAR(13),  -- 신청자 주민등록번호
  SBSCRB_DE TIMESTAMP,  -- 가입일시
  ENTRPRS_MBER_STTUS VARCHAR(15),  -- 회원상태코드
  ENTRPRS_MBER_PASSWORD VARCHAR(200),  -- 비밀번호(해시)
  ENTRPRS_MBER_PASSWORD_HINT VARCHAR(100) NOT NULL,  -- 비밀번호 힌트
  ENTRPRS_MBER_PASSWORD_CNSR VARCHAR(100) NOT NULL,  -- 비밀번호 정답
  GROUP_ID CHAR(20),  -- 그룹ID
  DETAIL_ADRES VARCHAR(100),  -- 상세주소
  ENTRPRS_END_TELNO VARCHAR(4),  -- 전화 끝번호
  AREA_NO VARCHAR(4),  -- 지역번호
  APPLCNT_EMAIL_ADRES VARCHAR(50),  -- 신청자 이메일
  TELNO VARCHAR(20),  -- 전화번호
  ESNTL_ID CHAR(20) NOT NULL,  -- 고유ID
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  CONSTRAINT FK_ENTRPRS_GROUP FOREIGN KEY(GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO(GROUP_ID) ON DELETE CASCADE
);
ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_EMPLYR FOREIGN KEY(SCRTY_DTRMN_TRGET_ID) REFERENCES TB_EMPLYR_INFO(EMPLYR_ID);
ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_ENTRPRS FOREIGN KEY(SCRTY_DTRMN_TRGET_ID) REFERENCES TB_ENTRPRS_MBER(ENTRPRS_MBER_ID);
ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_GNRL FOREIGN KEY(SCRTY_DTRMN_TRGET_ID) REFERENCES TB_GNRL_MBER(MBER_ID);
CREATE TABLE TB_BBS_MASTER (
  BBS_ID CHAR(20) NOT NULL PRIMARY KEY,  -- 게시판ID
  BBS_NM VARCHAR(255) NOT NULL,  -- 게시판명
  BBS_INTRCN VARCHAR(2400),  -- 게시판 소개
  BBS_TY_CODE CHAR(6) NOT NULL,  -- 게시판 유형코드
  BBS_ATTRB_CODE CHAR(6) NOT NULL,  -- 게시판 속성코드
  REPLY_POSBL_AT CHAR(1),  -- 답글 가능(Y/N)
  FILE_ATCH_POSBL_AT CHAR(1) NOT NULL,  -- 파일첨부 가능(Y/N)
  ATCH_POSBL_FILE_NUMBER NUMERIC(2) NOT NULL,  -- 첨부가능 파일 수
  ATCH_POSBL_FILE_SIZE NUMERIC(8),  -- 첨부가능 총 용량(단위: 시스템 정의)
  USE_AT CHAR(1) NOT NULL,  -- 사용여부(Y/N)
  TMPLAT_ID CHAR(20),  -- 템플릿ID
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_BBS_MASTER_OPTN (
  BBS_ID CHAR(20) DEFAULT '' NOT NULL PRIMARY KEY,  -- 게시판ID
  ANSWER_AT CHAR(1) DEFAULT '' NOT NULL,  -- 답변글 여부(Y/N)
  STSFDG_AT CHAR(1) DEFAULT '' NOT NULL,  -- 만족도 조사 사용(Y/N)
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT '1970-01-01 00:00:00.0' NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20) DEFAULT '' NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_BBS_USE (
  BBS_ID CHAR(20) NOT NULL,  -- 게시판ID
  TRGET_ID CHAR(20) DEFAULT '' NOT NULL,  -- 사용대상ID
  USE_AT CHAR(1) NOT NULL,  -- 사용여부(Y/N)
  REGIST_SE_CODE CHAR(6),  -- 등록구분코드
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  PRIMARY KEY(BBS_ID, TRGET_ID),
  CONSTRAINT FK_BBS_USE_MASTER FOREIGN KEY(BBS_ID) REFERENCES TB_BBS_MASTER(BBS_ID)
);
CREATE TABLE TB_BBS (
  NTT_ID NUMERIC(20) NOT NULL,  -- 게시물ID
  BBS_ID CHAR(20) NOT NULL,  -- 게시판ID
  NTT_NO NUMERIC(20),  -- 게시물 번호(정렬/표시용)
  NTT_SJ VARCHAR(2000),  -- 제목
  NTT_CN TEXT,  -- 내용
  ANSWER_AT CHAR(1),  -- 답변글 여부(Y/N)
  PARNTSCTT_NO NUMERIC(10),  -- 부모글 번호
  ANSWER_LC INTEGER,  -- 답변 계층(레벨)
  SORT_ORDR NUMERIC(8),  -- 정렬순서
  RDCNT NUMERIC(10),  -- 조회수
  USE_AT CHAR(1) NOT NULL,  -- 사용여부(Y/N)
  NTCE_BGNDE CHAR(20),  -- 공지 시작일시
  NTCE_ENDDE CHAR(20),  -- 공지 종료일시
  NTCR_ID VARCHAR(20),  -- 게시자ID
  NTCR_NM VARCHAR(20),  -- 게시자명
  PASSWORD VARCHAR(200),  -- 비밀번호(해시)
  ATCH_FILE_ID CHAR(20),  -- 첨부파일 묶음ID
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  PRIMARY KEY(NTT_ID, BBS_ID),
  CONSTRAINT FK_BBS_MASTER FOREIGN KEY(BBS_ID) REFERENCES TB_BBS_MASTER(BBS_ID)
);
CREATE TABLE TB_FILE (
  ATCH_FILE_ID CHAR(20) NOT NULL PRIMARY KEY,  -- 첨부파일 묶음ID
  CREAT_DT TIMESTAMP NOT NULL,  -- 생성시각
  USE_AT CHAR(1),  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_FILE_DETAIL (
  ATCH_FILE_ID CHAR(20) NOT NULL,  -- 첨부파일 묶음ID
  FILE_SN NUMERIC(10) NOT NULL,  -- 파일 일련번호
  FILE_STRE_COURS VARCHAR(2000) NOT NULL,  -- 파일 저장경로
  STRE_FILE_NM VARCHAR(255) NOT NULL,  -- 저장파일명
  ORIGNL_FILE_NM VARCHAR(255),  -- 원파일명
  FILE_EXTSN VARCHAR(20) NOT NULL,  -- 파일확장자
  FILE_CN TEXT,  -- 파일 내용/비고
  FILE_SIZE NUMERIC(8),  -- 파일크기(Byte)
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20),  -- 최종수정자ID
  PRIMARY KEY(ATCH_FILE_ID, FILE_SN),
  CONSTRAINT FK_FILE_DETAIL FOREIGN KEY(ATCH_FILE_ID) REFERENCES TB_FILE(ATCH_FILE_ID)
);
CREATE TABLE TB_SCHDUL_INFO (
  SCHDUL_ID CHAR(20) NOT NULL PRIMARY KEY,  -- 일정ID
  SCHDUL_SE CHAR(1),  -- 일정구분코드
  SCHDUL_DEPT_ID VARCHAR(20),  -- 부서ID
  SCHDUL_KND_CODE VARCHAR(20),  -- 일정종류코드
  SCHDUL_BEGINDE TIMESTAMP,  -- 시작일시
  SCHDUL_ENDDE TIMESTAMP,  -- 종료일시
  SCHDUL_NM VARCHAR(255),  -- 일정명
  SCHDUL_CN VARCHAR(2500),  -- 일정 내용
  SCHDUL_PLACE VARCHAR(255),  -- 장소
  SCHDUL_IPCR_CODE CHAR(1),  -- 중요도코드
  SCHDUL_CHARGER_ID VARCHAR(20),  -- 담당자ID
  ATCH_FILE_ID CHAR(20),  -- 첨부파일 묶음ID
  REPTIT_SE_CODE CHAR(3),  -- 반복구분코드
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_RESTDE (
  RESTDE_NO NUMERIC(20) NOT NULL PRIMARY KEY,  -- 휴일번호
  RESTDE_DE CHAR(8) NOT NULL,  -- 휴일일자
  RESTDE_NM VARCHAR(100) NOT NULL,  -- 휴일명
  RESTDE_DC VARCHAR(200),  -- 휴일설명
  RESTDE_SE_CODE CHAR(6),  -- 휴일구분상세코드
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE VIEW VW_USER_MASTER (ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID, USER_OCCP) AS SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR', ' ', OCCP_TY FROM TB_GNRL_MBER UNION ALL SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR', ORGNZT_ID, OCCP_TY FROM TB_EMPLYR_INFO UNION ALL SELECT ESNTL_ID, ENTRPRS_MBER_ID, ENTRPRS_MBER_PASSWORD, CMPNY_NM, ZIP, ADRES, APPLCNT_EMAIL_ADRES, ' ', 'ENT', ' ', '' FROM TB_ENTRPRS_MBER;
CREATE TABLE TB_FAQ_INFO (
  FAQ_ID CHAR(20) NOT NULL PRIMARY KEY,  -- FAQID
  QESTN_SJ VARCHAR(2000),  -- 질문제목
  QESTN_CN TEXT,  -- 질문내용
  ANSWER_CN TEXT,  -- 답변내용
  RDCNT NUMERIC(10) DEFAULT 0,  -- 조회수
  ATCH_FILE_ID CHAR(20),  -- 첨부파일 묶음ID
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_QA_INFO (
  QA_ID CHAR(20) NOT NULL PRIMARY KEY,  -- 질의응답ID
  QESTN_SJ VARCHAR(2000),  -- 질문제목
  QESTN_CN TEXT,  -- 질문내용
  WRITNG_PASSWORD VARCHAR(200),  -- 작성비밀번호(해시)
  AREA_NO VARCHAR(4),  -- 지역번호
  MIDDLE_TELNO VARCHAR(4),  -- 전화 중간번호
  END_TELNO VARCHAR(4),  -- 전화 끝번호
  EMAIL_ADRES VARCHAR(50),  -- 이메일
  EMAIL_ANSWER_AT CHAR(1) DEFAULT 'N',  -- 이메일답변여부
  WRTER_NM VARCHAR(50),  -- WRTER명
  WRITNG_DE CHAR(20),  -- 작성일자
  RDCNT NUMERIC(10) DEFAULT 0,  -- 조회수
  QNA_PROCESS_STTUS_CODE CHAR(6),  -- 질의응답처리상태상세코드
  ANSWER_CN TEXT,  -- 답변내용
  ANSWER_DE CHAR(20),  -- 답변일자
  ATCH_FILE_ID CHAR(20),  -- 첨부파일 묶음ID
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_TMPLAT_INFO (
  TMPLAT_ID CHAR(20) NOT NULL PRIMARY KEY,  -- 템플릿ID
  TMPLAT_NM VARCHAR(60),  -- 템플릿명
  TMPLAT_COURS VARCHAR(255),  -- 템플릿COURS
  TMPLAT_SE_CODE CHAR(6),  -- 템플릿구분상세코드
  USE_AT CHAR(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM TIMESTAMP,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR(20)  -- 최종수정자ID
);
CREATE TABLE TB_ROLES_HIERARCHY (
  PARNTS_ROLE varchar(30) NOT NULL,  -- 부모롤
  CHLDRN_ROLE varchar(30) NOT NULL,  -- 자식롤
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE)
);
CREATE TABLE TB_ROLE_INFO (
  ROLE_CODE varchar(50) DEFAULT '' NOT NULL,  -- 역할코드
  ROLE_NM varchar(60) NOT NULL,  -- 역할명
  ROLE_PTTRN varchar(300) DEFAULT NULL,  -- 롤PTTRN
  ROLE_DC varchar(200) DEFAULT NULL,  -- 역할설명
  ROLE_TY varchar(80) DEFAULT NULL,  -- 역할유형
  ROLE_SORT varchar(10) DEFAULT NULL,  -- 역할정렬
  ROLE_CREAT_DE char(20) NOT NULL,  -- 롤생성일자
  PRIMARY KEY (ROLE_CODE)
);
CREATE TABLE TB_AUTHOR_ROLE_RELATE (
  AUTHOR_CODE varchar(30) NOT NULL,  -- 권한코드
  ROLE_CODE varchar(50) NOT NULL,  -- 역할코드
  CREAT_DT TIMESTAMP DEFAULT NULL,  -- 생성시각
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE)
);
CREATE TABLE TB_ZIP (
  ZIP varchar(6) NOT NULL,  -- 우편번호
  SN NUMERIC(10,0) DEFAULT '0' NOT NULL,  -- 일련번호
  CTPRVN_NM varchar(20) DEFAULT NULL,  -- 시도명
  SIGNGU_NM varchar(20) DEFAULT NULL,  -- 시군구명
  EMD_NM varchar(60) DEFAULT NULL,  -- 읍면동명
  LI_BULD_NM varchar(60) DEFAULT NULL,  -- 리건물명
  LNBR_DONG_HO varchar(20) DEFAULT NULL,  -- 지번동호
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (ZIP,SN)
);
CREATE TABLE TB_BANNER (
  BANNER_ID char(20) DEFAULT '' NOT NULL,  -- 배너ID
  BANNER_NM varchar(60) NOT NULL,  -- 배너명
  LINK_URL varchar(255) NOT NULL,  -- 연계URL
  BANNER_IMAGE varchar(60) NOT NULL,  -- 배너이미지
  BANNER_DC varchar(200) DEFAULT NULL,  -- 배너설명
  REFLCT_AT char(1) NOT NULL,  -- REFLCT여부
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  BANNER_IMAGE_FILE varchar(60) DEFAULT NULL,  -- 배너이미지파일
  SORT_ORDR NUMERIC(8,0) DEFAULT NULL,  -- 정렬순서
  BANNER_TY varchar(10) DEFAULT 'MAIN',  -- 배너유형
  POPUP_LEFT INT DEFAULT NULL,  -- 팝업LEFT
  POPUP_TOP INT DEFAULT NULL,  -- 팝업TOP
  POPUP_WIDTH INT DEFAULT NULL,  -- 팝업너비
  POPUP_HEIGHT INT DEFAULT NULL,  -- 팝업HEIGHT
  POPUP_GROUP_AT char(1) DEFAULT 'N',  -- 팝업그룹여부
  EXPSR_BGNDE DATE DEFAULT NULL,  -- 노출시작일자
  EXPSR_ENDDE DATE DEFAULT NULL,  -- 노출종료일자
  PRIMARY KEY (BANNER_ID)
);
CREATE TABLE TB_INDVDL_INFO_POLICY (
  INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,  -- 개인정보정책ID
  INDVDL_INFO_POLICY_CN TEXT,  -- 개인정보정책내용
  INDVDL_INFO_POLICY_AGRE_AT char(1) DEFAULT NULL,  -- 개인정보정책동의여부
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  INDVDL_INFO_POLICY_NM varchar(255) DEFAULT NULL,  -- 개인정보정책명
  VER varchar(20) DEFAULT NULL,  -- 버전
  APLC_DE varchar(8) DEFAULT NULL,  -- 응용일자
  REPRSNT_AT char(1) DEFAULT 'N',  -- REPRSNT여부
  USE_AT char(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  PRIMARY KEY (INDVDL_INFO_POLICY_ID)
);
CREATE TABLE TB_PROGRM_LIST (
  PROGRM_FILE_NM varchar(60) DEFAULT '' NOT NULL,  -- 프로그램파일명
  PROGRM_STRE_PATH varchar(100) NOT NULL,  -- 프로그램STRE경로
  PROGRM_KOREAN_NM varchar(60) DEFAULT NULL,  -- 프로그램KOREAN명
  PROGRM_DC varchar(200) DEFAULT NULL,  -- 프로그램설명
  URL varchar(100) NOT NULL,  -- URL
  PRIMARY KEY (PROGRM_FILE_NM)
);
CREATE TABLE TB_MENU_INFO (
  MENU_NM varchar(60) NOT NULL,  -- 메뉴명
  PROGRM_FILE_NM varchar(60) NOT NULL,  -- 프로그램파일명
  MENU_NO NUMERIC(20,0) NOT NULL,  -- 메뉴번호
  UPPER_MENU_NO NUMERIC(20,0) DEFAULT NULL,  -- UPPER메뉴번호
  MENU_ORDR NUMERIC(5,0) NOT NULL,  -- 메뉴순서
  MENU_DC varchar(250) DEFAULT NULL,  -- 메뉴설명
  RELATE_IMAGE_PATH varchar(100) DEFAULT NULL,  -- 관련이미지경로
  RELATE_IMAGE_NM varchar(60) DEFAULT NULL,  -- 관련이미지명
  PRIMARY KEY (MENU_NO)
);
CREATE TABLE TB_MENU_CREAT_DTLS (
  MENU_NO NUMERIC(20,0) NOT NULL,  -- 메뉴번호
  AUTHOR_CODE varchar(30) NOT NULL,  -- 권한코드
  MAPNG_CREAT_ID varchar(30) DEFAULT NULL,  -- MAPNG생성ID
  PRIMARY KEY (MENU_NO,AUTHOR_CODE)
);
CREATE TABLE TB_QUSTNR_TMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QUSTNR_TMPLAT_TY varchar(100) DEFAULT NULL,  -- 설문템플릿유형
  QUSTNR_TMPLAT_DC varchar(2000) DEFAULT NULL,  -- 설문템플릿설명
  QUSTNR_TMPLAT_PATH_NM varchar(100) DEFAULT NULL,  -- 설문템플릿경로명
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  QUSTNR_TMPLAT_IMAGE_INFO blob,  -- 설문템플릿이미지정보
  PRIMARY KEY (QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_QESTNR_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_SJ varchar(255) DEFAULT NULL,  -- 설문제목
  QUSTNR_PURPS varchar(1000) DEFAULT NULL,  -- 설문목적
  QUSTNR_WRITNG_GUIDANCE_CN varchar(2000) DEFAULT NULL,  -- 설문작성안내내용
  QUSTNR_TRGET varchar(1000) DEFAULT NULL,  -- 설문대상
  QUSTNR_BGNDE char(20)  DEFAULT NULL,  -- 설문시작일자
  QUSTNR_ENDDE char(20) DEFAULT NULL,  -- 설문종료일자
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID)
);
CREATE TABLE TB_QUSTNR_QESITM (
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTN_SN NUMERIC(10,0) DEFAULT NULL,  -- 질문일련번호
  QESTN_TY_CODE char(1) DEFAULT NULL,  -- 질문유형상세코드
  QESTN_CN varchar(2500) DEFAULT NULL,  -- 질문내용
  MXMM_CHOISE_CO NUMERIC(5,0) DEFAULT NULL,  -- MXMMCHOISE수
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar(20) NOT NULL,  -- 최종수정자ID
  PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_QUSTNR_IEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_IEM_ID varchar(20) NOT NULL,  -- 설문항목ID
  IEM_SN NUMERIC(5,0) DEFAULT NULL,  -- 항목일련번호
  IEM_CN varchar(1000) DEFAULT NULL,  -- 항목내용
  ETC_ANSWER_AT char(1) DEFAULT NULL,  -- 기타답변여부
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID)
);
CREATE TABLE TB_QUSTNR_RESPOND_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_RESPOND_ID char(20) NOT NULL,  -- 설문응답ID
  SEXDSTN_CODE char(1) DEFAULT NULL,  -- 성별코드
  OCCP_TY_CODE varchar(10) DEFAULT NULL,  -- 직업유형상세코드
  RESPOND_NM varchar(50) DEFAULT NULL,  -- 응답명
  BRTHDY char(20) DEFAULT NULL,  -- 생년월일
  AREA_NO varchar(4) DEFAULT NULL,  -- 지역번호
  MIDDLE_TELNO varchar(4) DEFAULT NULL,  -- 전화 중간번호
  END_TELNO varchar(4) DEFAULT NULL,  -- 전화 끝번호
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID)
);
CREATE TABLE TB_QUSTNR_RSPNS_RESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,  -- 설문응답결과ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  RESPOND_ANSWER_CN varchar(1000) DEFAULT NULL,  -- 응답답변내용
  ETC_ANSWER_CN varchar(1000) DEFAULT NULL,  -- 기타답변내용
  RESPOND_NM varchar(50) DEFAULT NULL,  -- 응답명
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  QUSTNR_IEM_ID varchar(20) DEFAULT NULL,  -- 설문항목ID
  PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID char(20) NOT NULL,  -- 이용약관ID
  USE_STPLAT_NM varchar(100) DEFAULT NULL,  -- 이용약관명
  USE_STPLAT_CN TEXT,  -- 이용약관 내용
  INFO_PROVD_AGRE_CN TEXT,  -- 정보제공 동의 내용
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,  -- 최종수정자ID
  VER varchar(20) DEFAULT NULL,  -- 버전
  APLC_DE varchar(8) DEFAULT NULL,  -- 응용일자
  REPRSNT_AT char(1) DEFAULT 'N',  -- REPRSNT여부
  USE_AT char(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  PRIMARY KEY (USE_STPLAT_ID)
);
