-- 개정이력: 2026.06.17  구재호  전 DBMS TB_ 표준 명명 현행화
-- ============================================================
-- portal-site-boot PostgreSQL DDL (shtdb.sql HSQL 정본에서 생성)
-- 명명규칙: TB_ + snake_case / 감사컬럼 4종
-- 사용: psql -U postgres -d pst -f all_pst_ddl_postgresql.sql
-- ============================================================

DROP VIEW IF EXISTS VW_USER_MASTER CASCADE;
DROP TABLE IF EXISTS TB_STPLAT_INFO CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_RSPNS_RESULT CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_RESPOND_INFO CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_IEM CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_QESITM CASCADE;
DROP TABLE IF EXISTS TB_QESTNR_INFO CASCADE;
DROP TABLE IF EXISTS TB_QUSTNR_TMPLAT CASCADE;
DROP TABLE IF EXISTS TB_MENU_CREAT_DTLS CASCADE;
DROP TABLE IF EXISTS TB_MENU_INFO CASCADE;
DROP TABLE IF EXISTS TB_PROGRM_LIST CASCADE;
DROP TABLE IF EXISTS TB_INDVDL_INFO_POLICY CASCADE;
DROP TABLE IF EXISTS TB_BANNER CASCADE;
DROP TABLE IF EXISTS TB_ZIP CASCADE;
DROP TABLE IF EXISTS TB_AUTHOR_ROLE_RELATE CASCADE;
DROP TABLE IF EXISTS TB_ROLE_INFO CASCADE;
DROP TABLE IF EXISTS TB_ROLES_HIERARCHY CASCADE;
DROP TABLE IF EXISTS TB_TMPLAT_INFO CASCADE;
DROP TABLE IF EXISTS TB_QA_INFO CASCADE;
DROP TABLE IF EXISTS TB_FAQ_INFO CASCADE;
DROP TABLE IF EXISTS TB_RESTDE CASCADE;
DROP TABLE IF EXISTS TB_SCHDUL_INFO CASCADE;
DROP TABLE IF EXISTS TB_FILE_DETAIL CASCADE;
DROP TABLE IF EXISTS TB_FILE CASCADE;
DROP TABLE IF EXISTS TB_BBS CASCADE;
DROP TABLE IF EXISTS TB_BBS_USE CASCADE;
DROP TABLE IF EXISTS TB_BBS_MASTER_OPTN CASCADE;
DROP TABLE IF EXISTS TB_BBS_MASTER CASCADE;
DROP TABLE IF EXISTS TB_ENTRPRS_MBER CASCADE;
DROP TABLE IF EXISTS TB_GNRL_MBER CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_SCRTY_ESTBS CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_INFO_CHNG_DTLS CASCADE;
DROP TABLE IF EXISTS TB_EMPLYR_INFO CASCADE;
DROP TABLE IF EXISTS TB_ORGNZT_INFO CASCADE;
DROP TABLE IF EXISTS TB_AUTHOR_GROUP_INFO CASCADE;
DROP TABLE IF EXISTS TB_AUTHOR_INFO CASCADE;
DROP TABLE IF EXISTS TB_CMMN_DETAIL_CODE CASCADE;
DROP TABLE IF EXISTS TB_CMMN_CODE CASCADE;
DROP TABLE IF EXISTS TB_CMMN_CL_CODE CASCADE;
DROP TABLE IF EXISTS COMTECOPSEQ CASCADE;
DROP TABLE IF EXISTS IDS CASCADE;

CREATE TABLE IDS (TABLE_NAME VARCHAR(20) DEFAULT '' NOT NULL PRIMARY KEY, NEXT_ID NUMERIC(30) DEFAULT 0 NOT NULL);
CREATE TABLE COMTECOPSEQ (TABLE_NAME VARCHAR(20) DEFAULT '' NOT NULL PRIMARY KEY, NEXT_ID NUMERIC(30) DEFAULT 0 NOT NULL);
CREATE TABLE TB_CMMN_CL_CODE (CL_CODE CHAR(3) NOT NULL PRIMARY KEY, CL_CODE_NM VARCHAR(60), CL_CODE_DC VARCHAR(200), USE_AT CHAR(1), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_CMMN_CODE (CODE_ID VARCHAR(6) NOT NULL PRIMARY KEY, CODE_ID_NM VARCHAR(60), CODE_ID_DC VARCHAR(200), USE_AT CHAR(1), CL_CODE CHAR(3), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), CONSTRAINT FK_CMMN_CODE_CL FOREIGN KEY (CL_CODE) REFERENCES TB_CMMN_CL_CODE(CL_CODE));
CREATE TABLE TB_CMMN_DETAIL_CODE (CODE_ID VARCHAR(6) NOT NULL, CODE VARCHAR(15) NOT NULL, CODE_NM VARCHAR(60), CODE_DC VARCHAR(200), USE_AT CHAR(1), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), PRIMARY KEY(CODE_ID, CODE), CONSTRAINT FK_CMMN_DTL_CODE FOREIGN KEY(CODE_ID) REFERENCES TB_CMMN_CODE(CODE_ID));
CREATE TABLE TB_AUTHOR_INFO (AUTHOR_CODE VARCHAR(30) NOT NULL PRIMARY KEY, AUTHOR_NM VARCHAR(60) NOT NULL, AUTHOR_DC VARCHAR(200), AUTHOR_CREAT_DE CHAR(20) NOT NULL, FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_AUTHOR_GROUP_INFO (GROUP_ID CHAR(20) DEFAULT '' NOT NULL PRIMARY KEY, GROUP_NM VARCHAR(60) NOT NULL, GROUP_CREAT_DE CHAR(20) NOT NULL, GROUP_DC VARCHAR(100), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_ORGNZT_INFO (ORGNZT_ID CHAR(20) DEFAULT '' NOT NULL PRIMARY KEY, ORGNZT_NM VARCHAR(20) NOT NULL, ORGNZT_DC VARCHAR(100), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_EMPLYR_INFO (EMPLYR_ID VARCHAR(20) NOT NULL PRIMARY KEY, ORGNZT_ID CHAR(20), USER_NM VARCHAR(60) NOT NULL, PASSWORD VARCHAR(200) NOT NULL, EMPL_NO VARCHAR(20), IHIDNUM VARCHAR(13), SEXDSTN_CODE CHAR(1), BRTHDY CHAR(20), FXNUM VARCHAR(20), HOUSE_ADRES VARCHAR(100), PASSWORD_HINT VARCHAR(100) NOT NULL, PASSWORD_CNSR VARCHAR(100) NOT NULL, HOUSE_END_TELNO VARCHAR(4), AREA_NO VARCHAR(4), DETAIL_ADRES VARCHAR(100), ZIP VARCHAR(6), OFFM_TELNO VARCHAR(20), MBTLNUM VARCHAR(20), EMAIL_ADRES VARCHAR(50), OFCPS_NM VARCHAR(60), HOUSE_MIDDLE_TELNO VARCHAR(4), GROUP_ID CHAR(20), PSTINST_CODE CHAR(8), EMPLYR_STTUS_CODE VARCHAR(15) NOT NULL, ESNTL_ID CHAR(20) NOT NULL, CRTFC_DN_VALUE VARCHAR(20), SBSCRB_DE TIMESTAMP, OCCP_TY VARCHAR(10), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), CONSTRAINT FK_EMPLYR_GROUP FOREIGN KEY(GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO(GROUP_ID) ON DELETE CASCADE);
ALTER TABLE TB_EMPLYR_INFO ADD CONSTRAINT FK_EMPLYR_ORGNZT FOREIGN KEY(ORGNZT_ID) REFERENCES TB_ORGNZT_INFO(ORGNZT_ID);
CREATE TABLE TB_EMPLYR_INFO_CHNG_DTLS (EMPLYR_ID VARCHAR(20) NOT NULL, CHANGE_DE CHAR(20) NOT NULL, ORGNZT_ID CHAR(20), GROUP_ID CHAR(20), EMPL_NO VARCHAR(20) NOT NULL, SEXDSTN_CODE CHAR(1), BRTHDY CHAR(20), FXNUM VARCHAR(20), HOUSE_ADRES VARCHAR(100) NOT NULL, HOUSE_END_TELNO VARCHAR(4), AREA_NO VARCHAR(4), DETAIL_ADRES VARCHAR(100) NOT NULL, ZIP VARCHAR(6) NOT NULL, OFFM_TELNO VARCHAR(20), MBTLNUM VARCHAR(20) NOT NULL, EMAIL_ADRES VARCHAR(50), HOUSE_MIDDLE_TELNO VARCHAR(4), PSTINST_CODE CHAR(8), EMPLYR_STTUS_CODE VARCHAR(15) NOT NULL, ESNTL_ID CHAR(20), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), PRIMARY KEY(EMPLYR_ID, CHANGE_DE), CONSTRAINT FK_CHNG_EMPLYR FOREIGN KEY(EMPLYR_ID) REFERENCES TB_EMPLYR_INFO(EMPLYR_ID));
CREATE TABLE TB_EMPLYR_SCRTY_ESTBS (SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL PRIMARY KEY, MBER_TY_CODE VARCHAR(15), AUTHOR_CODE VARCHAR(30) NOT NULL, FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), CONSTRAINT FK_SCRTY_AUTHOR FOREIGN KEY(AUTHOR_CODE) REFERENCES TB_AUTHOR_INFO(AUTHOR_CODE));
CREATE TABLE TB_GNRL_MBER (MBER_ID VARCHAR(20) DEFAULT '' NOT NULL PRIMARY KEY, PASSWORD VARCHAR(200) NOT NULL, PASSWORD_HINT VARCHAR(100), PASSWORD_CNSR VARCHAR(100), IHIDNUM VARCHAR(13), MBER_NM VARCHAR(50) NOT NULL, ZIP VARCHAR(6), ADRES VARCHAR(100), AREA_NO VARCHAR(4), MBER_STTUS VARCHAR(15), DETAIL_ADRES VARCHAR(100), END_TELNO VARCHAR(4), MBTLNUM VARCHAR(20), GROUP_ID CHAR(20), MBER_FXNUM VARCHAR(20), MBER_EMAIL_ADRES VARCHAR(50), MIDDLE_TELNO VARCHAR(4), TELNO VARCHAR(20), SBSCRB_DE TIMESTAMP, SEXDSTN_CODE CHAR(1), ESNTL_ID CHAR(20) NOT NULL, OCCP_TY VARCHAR(10), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), CONSTRAINT FK_GNRL_GROUP FOREIGN KEY(GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO(GROUP_ID) ON DELETE CASCADE);
CREATE TABLE TB_ENTRPRS_MBER (ENTRPRS_MBER_ID VARCHAR(20) DEFAULT '' NOT NULL PRIMARY KEY, ENTRPRS_SE_CODE CHAR(15), BIZRNO VARCHAR(10), JURIRNO VARCHAR(13), CMPNY_NM VARCHAR(60) NOT NULL, CXFC VARCHAR(50), ZIP VARCHAR(6), ADRES VARCHAR(100), ENTRPRS_MIDDLE_TELNO VARCHAR(4), FXNUM VARCHAR(20), INDUTY_CODE CHAR(15), APPLCNT_NM VARCHAR(50) NOT NULL, APPLCNT_IHIDNUM VARCHAR(13), SBSCRB_DE TIMESTAMP, ENTRPRS_MBER_STTUS VARCHAR(15), ENTRPRS_MBER_PASSWORD VARCHAR(200), ENTRPRS_MBER_PASSWORD_HINT VARCHAR(100) NOT NULL, ENTRPRS_MBER_PASSWORD_CNSR VARCHAR(100) NOT NULL, GROUP_ID CHAR(20), DETAIL_ADRES VARCHAR(100), ENTRPRS_END_TELNO VARCHAR(4), AREA_NO VARCHAR(4), APPLCNT_EMAIL_ADRES VARCHAR(50), TELNO VARCHAR(20), ESNTL_ID CHAR(20) NOT NULL, FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), CONSTRAINT FK_ENTRPRS_GROUP FOREIGN KEY(GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO(GROUP_ID) ON DELETE CASCADE);
ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_EMPLYR FOREIGN KEY(SCRTY_DTRMN_TRGET_ID) REFERENCES TB_EMPLYR_INFO(EMPLYR_ID);
ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_ENTRPRS FOREIGN KEY(SCRTY_DTRMN_TRGET_ID) REFERENCES TB_ENTRPRS_MBER(ENTRPRS_MBER_ID);
ALTER TABLE TB_EMPLYR_SCRTY_ESTBS ADD CONSTRAINT FK_SCRTY_GNRL FOREIGN KEY(SCRTY_DTRMN_TRGET_ID) REFERENCES TB_GNRL_MBER(MBER_ID);
CREATE TABLE TB_BBS_MASTER (BBS_ID CHAR(20) NOT NULL PRIMARY KEY, BBS_NM VARCHAR(255) NOT NULL, BBS_INTRCN VARCHAR(2400), BBS_TY_CODE CHAR(6) NOT NULL, BBS_ATTRB_CODE CHAR(6) NOT NULL, REPLY_POSBL_AT CHAR(1), FILE_ATCH_POSBL_AT CHAR(1) NOT NULL, ATCH_POSBL_FILE_NUMBER NUMERIC(2) NOT NULL, ATCH_POSBL_FILE_SIZE NUMERIC(8), USE_AT CHAR(1) NOT NULL, TMPLAT_ID CHAR(20), FRST_REGIST_PNTTM TIMESTAMP NOT NULL, FRST_REGISTER_ID VARCHAR(20) NOT NULL, LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_BBS_MASTER_OPTN (BBS_ID CHAR(20) DEFAULT '' NOT NULL PRIMARY KEY, ANSWER_AT CHAR(1) DEFAULT '' NOT NULL, STSFDG_AT CHAR(1) DEFAULT '' NOT NULL, FRST_REGIST_PNTTM TIMESTAMP DEFAULT '1970-01-01 00:00:00.0' NOT NULL, FRST_REGISTER_ID VARCHAR(20) DEFAULT '' NOT NULL, LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_BBS_USE (BBS_ID CHAR(20) NOT NULL, TRGET_ID CHAR(20) DEFAULT '' NOT NULL, USE_AT CHAR(1) NOT NULL, REGIST_SE_CODE CHAR(6), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20) NOT NULL, LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), PRIMARY KEY(BBS_ID, TRGET_ID), CONSTRAINT FK_BBS_USE_MASTER FOREIGN KEY(BBS_ID) REFERENCES TB_BBS_MASTER(BBS_ID));
CREATE TABLE TB_BBS (NTT_ID NUMERIC(20) NOT NULL, BBS_ID CHAR(20) NOT NULL, NTT_NO NUMERIC(20), NTT_SJ VARCHAR(2000), NTT_CN TEXT, ANSWER_AT CHAR(1), PARNTSCTT_NO NUMERIC(10), ANSWER_LC INTEGER, SORT_ORDR NUMERIC(8), RDCNT NUMERIC(10), USE_AT CHAR(1) NOT NULL, NTCE_BGNDE CHAR(20), NTCE_ENDDE CHAR(20), NTCR_ID VARCHAR(20), NTCR_NM VARCHAR(20), PASSWORD VARCHAR(200), ATCH_FILE_ID CHAR(20), FRST_REGIST_PNTTM TIMESTAMP NOT NULL, FRST_REGISTER_ID VARCHAR(20) NOT NULL, LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), PRIMARY KEY(NTT_ID, BBS_ID), CONSTRAINT FK_BBS_MASTER FOREIGN KEY(BBS_ID) REFERENCES TB_BBS_MASTER(BBS_ID));
CREATE TABLE TB_FILE (ATCH_FILE_ID CHAR(20) NOT NULL PRIMARY KEY, CREAT_DT TIMESTAMP NOT NULL, USE_AT CHAR(1), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_FILE_DETAIL (ATCH_FILE_ID CHAR(20) NOT NULL, FILE_SN NUMERIC(10) NOT NULL, FILE_STRE_COURS VARCHAR(2000) NOT NULL, STRE_FILE_NM VARCHAR(255) NOT NULL, ORIGNL_FILE_NM VARCHAR(255), FILE_EXTSN VARCHAR(20) NOT NULL, FILE_CN TEXT, FILE_SIZE NUMERIC(8), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20), PRIMARY KEY(ATCH_FILE_ID, FILE_SN), CONSTRAINT FK_FILE_DETAIL FOREIGN KEY(ATCH_FILE_ID) REFERENCES TB_FILE(ATCH_FILE_ID));
CREATE TABLE TB_SCHDUL_INFO (SCHDUL_ID CHAR(20) NOT NULL PRIMARY KEY, SCHDUL_SE CHAR(1), SCHDUL_DEPT_ID VARCHAR(20), SCHDUL_KND_CODE VARCHAR(20), SCHDUL_BEGINDE TIMESTAMP, SCHDUL_ENDDE TIMESTAMP, SCHDUL_NM VARCHAR(255), SCHDUL_CN VARCHAR(2500), SCHDUL_PLACE VARCHAR(255), SCHDUL_IPCR_CODE CHAR(1), SCHDUL_CHARGER_ID VARCHAR(20), ATCH_FILE_ID CHAR(20), REPTIT_SE_CODE CHAR(3), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_RESTDE (RESTDE_NO NUMERIC(20) NOT NULL PRIMARY KEY, RESTDE_DE CHAR(8) NOT NULL, RESTDE_NM VARCHAR(100) NOT NULL, RESTDE_DC VARCHAR(200), RESTDE_SE_CODE CHAR(6), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE VIEW VW_USER_MASTER (ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID, USER_OCCP) AS SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR', ' ', OCCP_TY FROM TB_GNRL_MBER UNION ALL SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR', ORGNZT_ID, OCCP_TY FROM TB_EMPLYR_INFO UNION ALL SELECT ESNTL_ID, ENTRPRS_MBER_ID, ENTRPRS_MBER_PASSWORD, CMPNY_NM, ZIP, ADRES, APPLCNT_EMAIL_ADRES, ' ', 'ENT', ' ', '' FROM TB_ENTRPRS_MBER;
CREATE TABLE TB_FAQ_INFO (FAQ_ID CHAR(20) NOT NULL PRIMARY KEY, QESTN_SJ VARCHAR(2000), QESTN_CN TEXT, ANSWER_CN TEXT, RDCNT NUMERIC(10) DEFAULT 0, ATCH_FILE_ID CHAR(20), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_QA_INFO (QA_ID CHAR(20) NOT NULL PRIMARY KEY, QESTN_SJ VARCHAR(2000), QESTN_CN TEXT, WRITNG_PASSWORD VARCHAR(200), AREA_NO VARCHAR(4), MIDDLE_TELNO VARCHAR(4), END_TELNO VARCHAR(4), EMAIL_ADRES VARCHAR(50), EMAIL_ANSWER_AT CHAR(1) DEFAULT 'N', WRTER_NM VARCHAR(50), WRITNG_DE CHAR(20), RDCNT NUMERIC(10) DEFAULT 0, QNA_PROCESS_STTUS_CODE CHAR(6), ANSWER_CN TEXT, ANSWER_DE CHAR(20), ATCH_FILE_ID CHAR(20), FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_TMPLAT_INFO (TMPLAT_ID CHAR(20) NOT NULL PRIMARY KEY, TMPLAT_NM VARCHAR(60), TMPLAT_COURS VARCHAR(255), TMPLAT_SE_CODE CHAR(6), USE_AT CHAR(1) DEFAULT 'Y', FRST_REGIST_PNTTM TIMESTAMP, FRST_REGISTER_ID VARCHAR(20), LAST_UPDT_PNTTM TIMESTAMP, LAST_UPDUSR_ID VARCHAR(20));
CREATE TABLE TB_ROLES_HIERARCHY (
  PARNTS_ROLE varchar(30) NOT NULL,
  CHLDRN_ROLE varchar(30) NOT NULL,
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE)
);
CREATE TABLE TB_ROLE_INFO (
  ROLE_CODE varchar(50) DEFAULT '' NOT NULL,
  ROLE_NM varchar(60) NOT NULL,
  ROLE_PTTRN varchar(300) DEFAULT NULL,
  ROLE_DC varchar(200) DEFAULT NULL,
  ROLE_TY varchar(80) DEFAULT NULL,
  ROLE_SORT varchar(10) DEFAULT NULL,
  ROLE_CREAT_DE char(20) NOT NULL,
  PRIMARY KEY (ROLE_CODE)
);
CREATE TABLE TB_AUTHOR_ROLE_RELATE (
  AUTHOR_CODE varchar(30) NOT NULL,
  ROLE_CODE varchar(50) NOT NULL,
  CREAT_DT TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE)
);
CREATE TABLE TB_ZIP (
  ZIP varchar(6) NOT NULL,
  SN NUMERIC(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM varchar(20) DEFAULT NULL,
  SIGNGU_NM varchar(20) DEFAULT NULL,
  EMD_NM varchar(60) DEFAULT NULL,
  LI_BULD_NM varchar(60) DEFAULT NULL,
  LNBR_DONG_HO varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (ZIP,SN)
);
CREATE TABLE TB_BANNER (
  BANNER_ID char(20) DEFAULT '' NOT NULL,
  BANNER_NM varchar(60) NOT NULL,
  LINK_URL varchar(255) NOT NULL,
  BANNER_IMAGE varchar(60) NOT NULL,
  BANNER_DC varchar(200) DEFAULT NULL,
  REFLCT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  BANNER_IMAGE_FILE varchar(60) DEFAULT NULL,
  SORT_ORDR NUMERIC(8,0) DEFAULT NULL,
  BANNER_TY varchar(10) DEFAULT 'MAIN',
  POPUP_LEFT INT DEFAULT NULL,
  POPUP_TOP INT DEFAULT NULL,
  POPUP_WIDTH INT DEFAULT NULL,
  POPUP_HEIGHT INT DEFAULT NULL,
  POPUP_GROUP_AT char(1) DEFAULT 'N',
  EXPSR_BGNDE DATE DEFAULT NULL,
  EXPSR_ENDDE DATE DEFAULT NULL,
  PRIMARY KEY (BANNER_ID)
);
CREATE TABLE TB_INDVDL_INFO_POLICY (
  INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,
  INDVDL_INFO_POLICY_CN TEXT,
  INDVDL_INFO_POLICY_AGRE_AT char(1) DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  INDVDL_INFO_POLICY_NM varchar(255) DEFAULT NULL,
  VER varchar(20) DEFAULT NULL,
  APLC_DE varchar(8) DEFAULT NULL,
  REPRSNT_AT char(1) DEFAULT 'N',
  USE_AT char(1) DEFAULT 'Y',
  PRIMARY KEY (INDVDL_INFO_POLICY_ID)
);
CREATE TABLE TB_PROGRM_LIST (
  PROGRM_FILE_NM varchar(60) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH varchar(100) NOT NULL,
  PROGRM_KOREAN_NM varchar(60) DEFAULT NULL,
  PROGRM_DC varchar(200) DEFAULT NULL,
  URL varchar(100) NOT NULL,
  PRIMARY KEY (PROGRM_FILE_NM)
);
CREATE TABLE TB_MENU_INFO (
  MENU_NM varchar(60) NOT NULL,
  PROGRM_FILE_NM varchar(60) NOT NULL,
  MENU_NO NUMERIC(20,0) NOT NULL,
  UPPER_MENU_NO NUMERIC(20,0) DEFAULT NULL,
  MENU_ORDR NUMERIC(5,0) NOT NULL,
  MENU_DC varchar(250) DEFAULT NULL,
  RELATE_IMAGE_PATH varchar(100) DEFAULT NULL,
  RELATE_IMAGE_NM varchar(60) DEFAULT NULL,
  PRIMARY KEY (MENU_NO)
);
CREATE TABLE TB_MENU_CREAT_DTLS (
  MENU_NO NUMERIC(20,0) NOT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  MAPNG_CREAT_ID varchar(30) DEFAULT NULL,
  PRIMARY KEY (MENU_NO,AUTHOR_CODE)
);
CREATE TABLE TB_QUSTNR_TMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_TY varchar(100) DEFAULT NULL,
  QUSTNR_TMPLAT_DC varchar(2000) DEFAULT NULL,
  QUSTNR_TMPLAT_PATH_NM varchar(100) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  QUSTNR_TMPLAT_IMAGE_INFO blob,
  PRIMARY KEY (QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_QESTNR_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_SJ varchar(255) DEFAULT NULL,
  QUSTNR_PURPS varchar(1000) DEFAULT NULL,
  QUSTNR_WRITNG_GUIDANCE_CN varchar(2000) DEFAULT NULL,
  QUSTNR_TRGET varchar(1000) DEFAULT NULL,
  QUSTNR_BGNDE char(20)  DEFAULT NULL,
  QUSTNR_ENDDE char(20) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID)
);
CREATE TABLE TB_QUSTNR_QESITM (
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTN_SN NUMERIC(10,0) DEFAULT NULL,
  QESTN_TY_CODE char(1) DEFAULT NULL,
  QESTN_CN varchar(2500) DEFAULT NULL,
  MXMM_CHOISE_CO NUMERIC(5,0) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID varchar(20) NOT NULL,
  PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_QUSTNR_IEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_IEM_ID varchar(20) NOT NULL,
  IEM_SN NUMERIC(5,0) DEFAULT NULL,
  IEM_CN varchar(1000) DEFAULT NULL,
  ETC_ANSWER_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID)
);
CREATE TABLE TB_QUSTNR_RESPOND_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_RESPOND_ID char(20) NOT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  OCCP_TY_CODE varchar(1) DEFAULT NULL,
  RESPOND_NM varchar(50) DEFAULT NULL,
  BRTHDY char(20) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  MIDDLE_TELNO varchar(4) DEFAULT NULL,
  END_TELNO varchar(4) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID)
);
CREATE TABLE TB_QUSTNR_RSPNS_RESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  RESPOND_ANSWER_CN varchar(1000) DEFAULT NULL,
  ETC_ANSWER_CN varchar(1000) DEFAULT NULL,
  RESPOND_NM varchar(50) DEFAULT NULL,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  QUSTNR_IEM_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID char(20) NOT NULL,
  USE_STPLAT_NM varchar(100) DEFAULT NULL,
  USE_STPLAT_CN TEXT,
  INFO_PROVD_AGRE_CN TEXT,
  FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  VER varchar(20) DEFAULT NULL,
  APLC_DE varchar(8) DEFAULT NULL,
  REPRSNT_AT char(1) DEFAULT 'N',
  USE_AT char(1) DEFAULT 'Y',
  PRIMARY KEY (USE_STPLAT_ID)
);
